/* tests/test_modctx.c: the modulus contexts of include/adelefeld/modctx.h.

   Ground truth: tests/ref/vectors/m1-modctx/modctx.jsonl, generated by
   lanes/m1-modctx-b/gen_modctx_vectors.py from tests/ref/adfref/modctx_ref.py (CONVENTIONS
   legal: the vectors are the oracle, the C test does not import the reference).  The golden
   file tests/golden/dump.tsv carries the modctx bodies of the dump form with their statuses.
   The constructors, the coefficients and the statuses are those of docs/conventions.md 5.14,
   3.2 and 10.2; the reduction and the recombination are policies.md Lemma 17.

   The internal kernels adf_modctx_reduce / adf_modctx_recombine are declared here by hand;
   they are hidden symbols of the library (src/modctx.c), not part of the public interface.

   The tests also cover: every validation failure with *out untouched; the round trip integer
   to residues to integer for 1, 2, 64 and 128 blocks; the descriptor functions; two threads
   reading one context at the same time. */

#include <stdio.h>
#include <string.h>

#include <pthread.h>
#include <sys/mman.h>
#include <unistd.h>

#include <adelefeld/modctx.h>
#include <flint/ulong_extras.h>

#include "support/golden.h"
#include "support/jsonl.h"
#include "test_runner.h"

/* Hidden internal kernels of src/modctx.c (docs/conventions.md 5.14; policies.md Lemma 17). */
void adf_modctx_reduce(const adf_modctx_struct * ctx, const fmpz_t a, ulong * res);
void adf_modctx_recombine(fmpz_t out, const adf_modctx_struct * ctx, const ulong * res);

/* ------------------------------------------------------------------ JSON helpers */

static int
json_fmpz(fmpz_t v, const jsonl_value * j, jsonl_error_t * err)
{
    const char * text = jsonl_int_text(j, err);
    if (text == NULL)
        return 0;
    return fmpz_set_str(v, text, 10) == 0;
}

static int
json_ui(ulong * v, const jsonl_value * j, jsonl_error_t * err)
{
    fmpz_t t;
    int ok;
    const char * text = jsonl_int_text(j, err);
    if (text == NULL)
        return 0;
    fmpz_init(t);
    ok = fmpz_set_str(t, text, 10) == 0;
    if (ok)
        *v = fmpz_get_ui(t);
    fmpz_clear(t);
    return ok;
}

/* The unsigned words of a JSON array. */
static ulong *
json_ulongs(const jsonl_value * arr, slong * n, jsonl_error_t * err)
{
    size_t i, sz = jsonl_size(arr);
    ulong * v = flint_malloc(sz > 0 ? sz * sizeof(ulong) : sizeof(ulong));
    for (i = 0; i < sz; i++)
    {
        const jsonl_value * e = jsonl_at(arr, i, err);
        if (e == NULL || !json_ui(&v[i], e, err))
        {
            flint_free(v);
            return NULL;
        }
    }
    *n = (slong) sz;
    return v;
}

/* Compare a context with (K, blocks) of a vector record. */
static void
check_ctx(const adf_modctx_struct * ctx, const fmpz_t K, const ulong * blocks, slong k)
{
    fmpz_t gotK;
    slong i;

    fmpz_init(gotK);
    adf_modctx_get_modulus(gotK, ctx);
    ADF_CHECK(fmpz_equal(gotK, K));
    fmpz_clear(gotK);
    ADF_CHECK(adf_modctx_nblocks(ctx) == k);
    for (i = 0; i < k; i++)
        ADF_CHECK(adf_modctx_block(ctx, i) == blocks[i]);
}

/* Read the "result": {K, blocks} of a record and compare with ctx. */
static void
check_result(const adf_modctx_struct * ctx, const jsonl_value * result, jsonl_error_t * err)
{
    const jsonl_value * jK, * jb;
    fmpz_t K;
    ulong * blocks;
    slong k;

    ADF_CHECK(jsonl_field(result, "K", &jK, err) == 1);
    ADF_CHECK(jsonl_field(result, "blocks", &jb, err) == 1);
    fmpz_init(K);
    ADF_CHECK(json_fmpz(K, jK, err));
    blocks = json_ulongs(jb, &k, err);
    ADF_CHECK(blocks != NULL);
    if (blocks != NULL)
    {
        check_ctx(ctx, K, blocks, k);
        flint_free(blocks);
    }
    fmpz_clear(K);
}

/* The integer of the result, or 0. */
static slong
record_status(const jsonl_value * rec, jsonl_error_t * err)
{
    const jsonl_value * js;
    const char * name;
    size_t len;
    int i;

    if (!jsonl_field(rec, "status", &js, err))
        return -1;
    name = jsonl_string(js, &len, err);
    if (name == NULL)
        return -1;
    for (i = 0; i <= ADF_LIMIT; i++)
        if (strlen(adf_status_str(i)) == len && memcmp(adf_status_str(i), name, len) == 0)
            return i;
    return -1;
}

/* ------------------------------------------------------------------ the vector oracle */

ADF_TEST(vectors_modctx)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    size_t ri, n = 0;

    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/m1-modctx/modctx.jsonl", &f, &err) == 1, "%s",
                  jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (ri = 0; ri < jsonl_count(f); ri++)
    {
        const jsonl_value * rec = jsonl_record(f, ri);
        const jsonl_value * jop;
        const char * op;
        size_t oplen;
        adf_modctx_struct * sentinel = (adf_modctx_struct *) (void *) 0x1;
        adf_modctx_struct * ctx = sentinel;
        slong status;
        int expected = record_status(rec, &err);

        ADF_CHECK(jsonl_field(rec, "op", &jop, &err) == 1);
        op = jsonl_string(jop, &oplen, &err);
        ADF_CHECK(op != NULL);

        if (oplen == 10 && memcmp(op, "new_blocks", 10) == 0)
        {
            const jsonl_value * jq;
            ulong * q;
            slong k;
            ADF_CHECK(jsonl_field(rec, "q", &jq, &err) == 1);
            q = json_ulongs(jq, &k, &err);
            ADF_CHECK(q != NULL);
            status = adf_modctx_new_blocks(&ctx, q, k);
            flint_free(q);
        }
        else if (oplen == 16 && memcmp(op, "new_prime_powers", 16) == 0)
        {
            const jsonl_value * jp, * je;
            ulong * p, * e;
            slong kp, ke;
            ADF_CHECK(jsonl_field(rec, "p", &jp, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "e", &je, &err) == 1);
            p = json_ulongs(jp, &kp, &err);
            e = json_ulongs(je, &ke, &err);
            ADF_CHECK(p != NULL && e != NULL && kp == ke);
            status = adf_modctx_new_prime_powers(&ctx, p, e, kp);
            flint_free(p);
            flint_free(e);
        }
        else if (oplen == 8 && memcmp(op, "new_fmpz", 8) == 0)
        {
            const jsonl_value * jK;
            fmpz_t K;
            ADF_CHECK(jsonl_field(rec, "K", &jK, &err) == 1);
            fmpz_init(K);
            ADF_CHECK(json_fmpz(K, jK, &err));
            status = adf_modctx_new_fmpz(&ctx, K);
            fmpz_clear(K);
        }
        else if (oplen == 13 && memcmp(op, "new_factorial", 13) == 0)
        {
            const jsonl_value * jn;
            ulong nv;
            ADF_CHECK(jsonl_field(rec, "n", &jn, &err) == 1);
            ADF_CHECK(json_ui(&nv, jn, &err));
            status = adf_modctx_new_factorial(&ctx, nv);
        }
        else if (oplen == 17 && memcmp(op, "new_primorial_pow", 17) == 0)
        {
            const jsonl_value * jn, * je;
            ulong nv, ev;
            ADF_CHECK(jsonl_field(rec, "n", &jn, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "e", &je, &err) == 1);
            ADF_CHECK(json_ui(&nv, jn, &err));
            ADF_CHECK(json_ui(&ev, je, &err));
            status = adf_modctx_new_primorial_pow(&ctx, nv, ev);
        }
        else if (oplen == 9 && memcmp(op, "roundtrip", 9) == 0)
        {
            const jsonl_value * jK, * jb, * ja, * result, * jr, * jback;
            fmpz_t K, a, back, expect_back;
            ulong * blocks;
            slong k, i;
            ulong * res;
            ADF_CHECK(jsonl_field(rec, "K", &jK, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "blocks", &jb, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "result", &result, &err) == 1);
            ADF_CHECK(jsonl_field(result, "res", &jr, &err) == 1);
            ADF_CHECK(jsonl_field(result, "back", &jback, &err) == 1);
            fmpz_init(K);
            fmpz_init(a);
            fmpz_init(back);
            fmpz_init(expect_back);
            ADF_CHECK(json_fmpz(K, jK, &err));
            ADF_CHECK(json_fmpz(a, ja, &err));
            blocks = json_ulongs(jb, &k, &err);
            ADF_CHECK(blocks != NULL);
            status = adf_modctx_new_blocks(&ctx, blocks, k);
            ADF_CHECK(status == ADF_OK);
            ADF_CHECK(ctx != sentinel);
            if (ctx != sentinel)
            {
                check_ctx(ctx, K, blocks, k);
                res = flint_malloc((size_t) k * sizeof(ulong));
                adf_modctx_reduce(ctx, a, res);
                for (i = 0; i < k; i++)
                {
                    ulong want;
                    ADF_CHECK(json_ui(&want, jsonl_at(jr, (size_t) i, &err), &err));
                    ADF_CHECK_MSG(res[i] == want, "res[%ld] = %lu != %lu", (long) i, res[i], want);
                }
                adf_modctx_recombine(back, ctx, res);
                ADF_CHECK(json_fmpz(expect_back, jback, &err));
                ADF_CHECK(fmpz_equal(back, expect_back));
                flint_free(res);
                adf_modctx_free(ctx);
                ctx = sentinel;
            }
            fmpz_clear(K);
            fmpz_clear(a);
            fmpz_clear(back);
            fmpz_clear(expect_back);
            flint_free(blocks);
            n++;
            continue;
        }
        else if (oplen == 4 && memcmp(op, "dump", 4) == 0)
        {
            const jsonl_value * jK, * jb, * jr;
            const char * text;
            size_t tlen, dlen;
            char * got;
            fmpz_t K;
            ulong * blocks;
            slong k;
            ADF_CHECK(jsonl_field(rec, "K", &jK, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "blocks", &jb, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "result", &jr, &err) == 1);
            text = jsonl_string(jr, &tlen, &err);
            ADF_CHECK(text != NULL);
            fmpz_init(K);
            ADF_CHECK(json_fmpz(K, jK, &err));
            blocks = json_ulongs(jb, &k, &err);
            ADF_CHECK(blocks != NULL);
            if (k == 0)
                status = adf_modctx_new_fmpz(&ctx, K);
            else
                status = adf_modctx_new_blocks(&ctx, blocks, k);
            ADF_CHECK(status == ADF_OK);
            if (ctx != sentinel)
            {
                got = adf_modctx_dump_str(&dlen, ctx);
                ADF_CHECK(got[dlen] == '\0');
                ADF_CHECK_MSG(dlen == tlen && memcmp(got, text, tlen) == 0,
                              "dump \"%.*s\" != \"%.*s\"", (int) dlen, got, (int) tlen, text);
                flint_free(got);
                adf_modctx_free(ctx);
                ctx = sentinel;
            }
            fmpz_clear(K);
            flint_free(blocks);
            n++;
            continue;
        }
        else if (oplen == 9 && memcmp(op, "from_dump", 9) == 0)
        {
            const jsonl_value * jt, * jocc, * jmi, * jml;
            const char * text;
            size_t tlen, occ;
            ulong mi, ml;
            adf_text_limits_t lim;
            ADF_CHECK(jsonl_field(rec, "text", &jt, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "occurrence", &jocc, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "max_items", &jmi, &err) == 1);
            ADF_CHECK(jsonl_field(rec, "max_len", &jml, &err) == 1);
            text = jsonl_string(jt, &tlen, &err);
            ADF_CHECK(text != NULL);
            ADF_CHECK(json_ui(&mi, jmi, &err));
            ADF_CHECK(json_ui(&ml, jml, &err));
            {
                fmpz_t occz;
                fmpz_init(occz);
                ADF_CHECK(json_fmpz(occz, jocc, &err));
                occ = (size_t) fmpz_get_ui(occz);
                fmpz_clear(occz);
            }
            adf_text_limits_default(&lim);
            lim.max_items = (slong) mi;
            lim.max_len = (size_t) ml;
            status = adf_modctx_new_from_dump(&ctx, text, tlen, occ, &lim);
        }
        else
        {
            ADF_CHECK_MSG(0, "unknown op \"%.*s\"", (int) oplen, op);
            continue;
        }

        if (expected >= 0)
        {
            ADF_CHECK_MSG(status == expected, "op \"%.*s\": status %s != %s", (int) oplen, op,
                          adf_status_str(status), adf_status_str(expected));
            ADF_CHECK_MSG(ctx == sentinel, "op \"%.*s\": *out was written on a failure",
                          (int) oplen, op);
        }
        else
        {
            const jsonl_value * result;
            ADF_CHECK_MSG(status == ADF_OK, "op \"%.*s\": status %s != OK", (int) oplen, op,
                          adf_status_str(status));
            ADF_CHECK(ctx != sentinel);
            if (ctx != sentinel)
            {
                if (jsonl_field(rec, "result", &result, &err))
                    check_result(ctx, result, &err);
                adf_modctx_free(ctx);
            }
        }
        n++;
    }
    ADF_CHECK(n == jsonl_count(f));
    jsonl_close(f);
}

/* ------------------------------------------------------------------ the dump golden file */

ADF_TEST(golden_modctx_bodies)
{
    golden_error_t err;
    golden_file * f = NULL;
    size_t i, n = 0;

    ADF_CHECK_MSG(golden_open("tests/golden/dump.tsv", GOLDEN_DEFAULT_MAX_INPUT, &f, &err) == 1,
                  "%s", golden_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < golden_count(f); i++)
    {
        const golden_record * r = golden_record_at(f, i);
        adf_modctx_struct * sentinel = (adf_modctx_struct *) (void *) 0x1;
        adf_modctx_struct * ctx = sentinel;
        int status;

        if (r->input_len < 15 || memcmp(r->input, "adf1 Q modctx ", 14) != 0)
            continue;
        status = adf_modctx_new_from_dump(&ctx, r->input, r->input_len, 0, NULL);
        if (r->is_status)
        {
            ADF_CHECK_MSG(status >= 0 && strcmp(adf_status_str(status), r->status) == 0,
                          "input \"%s\": status %s, expected %s", r->input,
                          adf_status_str(status), r->status);
            ADF_CHECK(ctx == sentinel);
        }
        else
        {
            size_t dlen;
            char * got;
            ADF_CHECK_MSG(status == ADF_OK, "input \"%s\": status %s", r->input,
                          adf_status_str(status));
            if (status == ADF_OK)
            {
                got = adf_modctx_dump_str(&dlen, ctx);
                ADF_CHECK_MSG(dlen == r->expected_len && memcmp(got, r->expected, dlen) == 0,
                              "input \"%s\" dumped \"%.*s\", expected \"%s\"", r->input,
                              (int) dlen, got, r->expected);
                flint_free(got);
                adf_modctx_free(ctx);
            }
        }
        n++;
    }
    ADF_CHECK(n == 13);                    /* the modctx bodies of the file */
    golden_close(f);
}

/* ------------------------------------------------------------------ validations */

ADF_TEST(constructor_validations_touch_no_output)
{
    adf_modctx_struct * sentinel = (adf_modctx_struct *) (void *) 0x1;
    adf_modctx_struct * ctx;
    ulong q[3];
    ulong p[3], e[3];
    fmpz_t K;

    /* new_blocks: q of 0 or 1, a non-coprime pair, q = NULL with k > 0 */
    ctx = sentinel;
    q[0] = 0;
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, 1) == ADF_DOMAIN && ctx == sentinel);
    q[0] = 1;
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, 1) == ADF_DOMAIN && ctx == sentinel);
    q[0] = 2;
    q[1] = 2;
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, 2) == ADF_DOMAIN && ctx == sentinel);
    q[0] = 6;
    q[1] = 10;
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, 2) == ADF_DOMAIN && ctx == sentinel);
    ADF_CHECK(adf_modctx_new_blocks(&ctx, NULL, 3) == ADF_DOMAIN && ctx == sentinel);
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, -1) == ADF_DOMAIN && ctx == sentinel);

    /* new_prime_powers: composite, repeated prime, exponent 0, power >= 2^64 */
    ctx = sentinel;
    p[0] = 4;
    e[0] = 1;
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, 1) == ADF_DOMAIN && ctx == sentinel);
    p[0] = 0;
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, 1) == ADF_DOMAIN && ctx == sentinel);
    p[0] = 2;
    p[1] = 2;
    e[0] = 1;
    e[1] = 1;
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, 2) == ADF_DOMAIN && ctx == sentinel);
    p[0] = 2;
    e[0] = 0;
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, 1) == ADF_DOMAIN && ctx == sentinel);
    p[0] = 2;
    e[0] = 64;
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, 1) == ADF_UNSUPPORTED && ctx == sentinel);
    p[0] = 3;
    e[0] = 41;
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, 1) == ADF_UNSUPPORTED && ctx == sentinel);
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, NULL, e, 1) == ADF_DOMAIN && ctx == sentinel);
    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, -1) == ADF_DOMAIN && ctx == sentinel);

    /* new_fmpz: K < 1 */
    ctx = sentinel;
    fmpz_init(K);
    fmpz_set_si(K, 0);
    ADF_CHECK(adf_modctx_new_fmpz(&ctx, K) == ADF_DOMAIN && ctx == sentinel);
    fmpz_set_si(K, -7);
    ADF_CHECK(adf_modctx_new_fmpz(&ctx, K) == ADF_DOMAIN && ctx == sentinel);
    fmpz_clear(K);

    /* new_from_dump: too many blocks is LIMIT with *out untouched */
    ctx = sentinel;
    {
        adf_text_limits_t lim;
        adf_text_limits_default(&lim);
        lim.max_items = 1;
        ADF_CHECK(adf_modctx_new_from_dump(&ctx, "adf1 Q modctx 6 2 2 3", 21, 0, &lim) ==
                  ADF_LIMIT);
        ADF_CHECK(ctx == sentinel);
    }
}

/* ------------------------------------------------------------------ the descriptor */

ADF_TEST(ctx_desc_and_match)
{
    adf_ctx_desc_t d;
    adf_modctx_struct * ctx = NULL;
    ulong q[2];
    fmpz_t K;
    size_t len;
    char * s;

    adf_ctx_desc_init(&d);
    ADF_CHECK(fmpz_is_one(d.K) == 1);
    ADF_CHECK(d.k == 0);
    ADF_CHECK(d.q == NULL);

    q[0] = 2;
    q[1] = 3;
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, 2) == ADF_OK);
    ADF_CHECK(adf_modctx_matches_desc(NULL, &d) == 0);
    ADF_CHECK(adf_modctx_matches_desc(ctx, NULL) == 0);
    ADF_CHECK(adf_modctx_matches_desc(ctx, &d) == 0);
    fmpz_set_ui(d.K, 6);
    d.k = 2;
    d.q = flint_malloc(2 * sizeof(ulong));
    d.q[0] = 2;
    d.q[1] = 3;
    ADF_CHECK(adf_modctx_matches_desc(ctx, &d) == 1);
    d.q[1] = 5;
    ADF_CHECK(adf_modctx_matches_desc(ctx, &d) == 0);
    d.q[1] = 3;
    d.k = 1;
    ADF_CHECK(adf_modctx_matches_desc(ctx, &d) == 0);
    adf_ctx_desc_clear(&d);

    /* dump and reload: the reloaded context matches the descriptor of the dump. */
    adf_ctx_desc_init(&d);
    s = adf_modctx_dump_str(&len, ctx);
    {
        adf_modctx_struct * copy = NULL;
        ADF_CHECK(adf_modctx_new_from_dump(&copy, s, len, 0, NULL) == ADF_OK);
        fmpz_init(K);
        adf_modctx_get_modulus(K, copy);
        ADF_CHECK(fmpz_equal_si(K, 6));
        ADF_CHECK(adf_modctx_nblocks(copy) == 2);
        ADF_CHECK(adf_modctx_block(copy, 0) == 2 && adf_modctx_block(copy, 1) == 3);
        fmpz_set(d.K, K);
        d.k = 2;
        d.q = flint_malloc(2 * sizeof(ulong));
        d.q[0] = 2;
        d.q[1] = 3;
        ADF_CHECK(adf_modctx_matches_desc(copy, &d) == 1);
        fmpz_clear(K);
        adf_modctx_free(copy);
    }
    flint_free(s);
    adf_ctx_desc_clear(&d);
    adf_modctx_free(ctx);
}

/* ------------------------------------------------------------------ threads */

typedef struct
{
    const adf_modctx_struct * ctx;
    int id;
    int ok;
} thr_arg;

static void *
thread_reader(void * arg)
{
    thr_arg * t = arg;
    fmpz_t x, y, r;
    ulong * res;
    slong k = adf_modctx_nblocks(t->ctx);
    int it;

    fmpz_init(x);
    fmpz_init(y);
    fmpz_init(r);
    res = flint_malloc((size_t) k * sizeof(ulong));
    for (it = 0; it < 2000; it++)
    {
        slong i;
        fmpz_set_ui(x, 1000003UL * (ulong) (t->id + 1) + (ulong) it);
        /* read the immutable fields */
        for (i = 0; i < k; i++)
            (void) adf_modctx_block(t->ctx, i);
        adf_modctx_reduce(t->ctx, x, res);
        adf_modctx_recombine(y, t->ctx, res);
        adf_modctx_get_modulus(r, t->ctx);
        fmpz_mod(r, x, r);
        if (!fmpz_equal(y, r))
        {
            t->ok = 0;
            break;
        }
    }
    if (it == 2000)
        t->ok = 1;
    flint_free(res);
    fmpz_clear(x);
    fmpz_clear(y);
    fmpz_clear(r);
    /* docs/conventions.md 4.5: a thread that used FLINT calls its own cleanup before it
       exits; the library itself never starts or cleans up a thread. */
    flint_cleanup();
    return NULL;
}

ADF_TEST(two_threads_read_one_context)
{
    adf_modctx_struct * ctx = NULL;
    pthread_t th[2];
    thr_arg args[2];
    ulong * q;
    slong k, i;
    int r0, r1;

    /* 64 pairwise coprime blocks */
    k = 64;
    q = flint_malloc((size_t) k * sizeof(ulong));
    {
        ulong p = 2;
        for (i = 0; i < k; i++)
        {
            q[i] = p;
            p = n_nextprime(p, 0);
        }
    }
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, k) == ADF_OK);
    flint_free(q);
    args[0].ctx = ctx;
    args[0].id = 0;
    args[0].ok = 0;
    args[1].ctx = ctx;
    args[1].id = 1;
    args[1].ok = 0;
    r0 = pthread_create(&th[0], NULL, thread_reader, &args[0]);
    r1 = pthread_create(&th[1], NULL, thread_reader, &args[1]);
    ADF_CHECK(r0 == 0 && r1 == 0);
    if (r0 == 0)
        pthread_join(th[0], NULL);
    if (r1 == 0)
        pthread_join(th[1], NULL);
    ADF_CHECK(args[0].ok == 1);
    ADF_CHECK(args[1].ok == 1);
    adf_modctx_free(ctx);
}

/* ------------------------------------------------------------------ free(NULL) and the offsets */

ADF_TEST(free_null_and_layout)
{
    adf_modctx_free(NULL);
    ADF_CHECK(sizeof(adf_ctx_desc_t) == 24);
    ADF_CHECK(ADF_ALIGNOF(adf_ctx_desc_t) == 8);
}

/* ------------------------------------------------------------------ dump edge cases */

/* Call new_from_dump on a text of `len` bytes and return the status. */
static int
from_dump_status(const char * text, size_t len)
{
    adf_modctx_struct * ctx = NULL;
    int st = adf_modctx_new_from_dump(&ctx, text, len, 0, NULL);
    adf_modctx_free(ctx);
    return st;
}

/* The byte length of a literal, embedded NUL included. */
#define FDS(lit) from_dump_status((lit), sizeof(lit) - 1)

ADF_TEST(from_dump_edge_cases)
{
    adf_text_limits_t lim;
    adf_modctx_struct * ctx = NULL;

    /* a forbidden byte: NUL and 0x01 (stage 2, before the grammar) */
    ADF_CHECK(FDS("adf1 Q modctx 6 1 6\x00") == ADF_PARSE);
    ADF_CHECK(FDS("adf1 Q modctx 6 1 6\x01") == ADF_PARSE);
    ADF_CHECK(FDS("adf\x00") == ADF_PARSE);

    /* the version: adf0 is UNSUPPORTED, adf01 is PARSE */
    ADF_CHECK(FDS("adf0 Q modctx 6 1 6") == ADF_UNSUPPORTED);
    ADF_CHECK(FDS("adf01 Q modctx 6 1 6") == ADF_PARSE);
    ADF_CHECK(FDS("adf2 Q modctx 6 1 6") == ADF_UNSUPPORTED);

    /* hex tokens: a leading 'a' and a later 'a' are accepted, 'g' and '-0' are not */
    ADF_CHECK(FDS("adf1 Q modctx a 0") == ADF_OK);
    ADF_CHECK(FDS("adf1 Q modctx 1a 0") == ADF_OK);
    ADF_CHECK(FDS("adf1 Q modctx g 0") == ADF_PARSE);
    ADF_CHECK(FDS("adf1 Q modctx -0 0") == ADF_PARSE);
    ADF_CHECK(FDS("adf1 Q modctx 07 1 7") == ADF_PARSE);
    ADF_CHECK(FDS("adf1 Q modctx 6 1 -6") == ADF_DOMAIN);

    /* a non-coprime pair whose product still equals K is DOMAIN */
    ADF_CHECK(FDS("adf1 Q modctx 8 2 2 4") == ADF_DOMAIN);

    /* a count that does not fit a size_t is a grammar failure, not a limit */
    ADF_CHECK(FDS("adf1 Q modctx 6 fffffffffffffffff 6") == ADF_PARSE);

    /* limits: max_items = 0 permits k = 0 and forbids k = 1 */
    adf_text_limits_default(&lim);
    lim.max_items = 0;
    ADF_CHECK(adf_modctx_new_from_dump(&ctx, "adf1 Q modctx 6 0", 17, 0, &lim) == ADF_OK);
    adf_modctx_free(ctx);
    ctx = NULL;
    ADF_CHECK(adf_modctx_new_from_dump(&ctx, "adf1 Q modctx 6 1 6", 19, 0, &lim) == ADF_LIMIT);
    ADF_CHECK(ctx == NULL);
}

/* The same body, but a context with many blocks: a heap under-allocation in the loader
   corrupts memory and a wrong block count is caught by the round trip. */
ADF_TEST(from_dump_many_blocks)
{
    ulong q[2000];
    adf_modctx_struct * ctx = NULL;
    adf_modctx_struct * copy = NULL;
    char * text;
    size_t len, dlen;
    ulong p = 2;
    int i;

    for (i = 0; i < 2000; i++)
    {
        q[i] = p;
        p = n_nextprime(p, 0);
    }
    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, 2000) == ADF_OK);
    text = adf_modctx_dump_str(&len, ctx);
    ADF_CHECK(adf_modctx_new_from_dump(&copy, text, len, 0, NULL) == ADF_OK);
    ADF_CHECK(adf_modctx_nblocks(copy) == 2000);
    for (i = 0; i < 2000; i++)
        ADF_CHECK(adf_modctx_block(copy, i) == q[i]);
    {
        char * again = adf_modctx_dump_str(&dlen, copy);
        ADF_CHECK(dlen == len && memcmp(again, text, len) == 0);
        flint_free(again);
    }
    adf_modctx_free(copy);
    adf_modctx_free(ctx);
    flint_free(text);
}

/* A text with no terminating NUL at the end of a mapped page: the last byte is the last
   byte of the mapping and the next page is inaccessible.  A parser that reads s[len] for a
   lookahead faults; new_from_dump must not.  This is the check of conventions 8.1. */
ADF_TEST(dump_input_without_terminator)
{
    long pg = sysconf(_SC_PAGESIZE);
    const char * cases[] = {"adf1", "adf1 Q ", "adf1 Q", "adf1 Q modctx",
                            "adf1 Q modctx 6 2 2", "adf1 Q modctx 6",
                            "adf1 Q modctx -"};
    size_t n = sizeof(cases) / sizeof(cases[0]);
    size_t i;

    ADF_CHECK(pg > 0);
    if (pg <= 0)
        return;
    for (i = 0; i < n; i++)
    {
        size_t len = strlen(cases[i]);
        char * base = mmap(NULL, (size_t) pg * 2, PROT_READ | PROT_WRITE,
                           MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
        char * p;
        int st;

        ADF_CHECK(base != MAP_FAILED);
        if (base == MAP_FAILED)
            continue;
        ADF_CHECK(mprotect(base + pg, (size_t) pg, PROT_NONE) == 0);
        p = base + pg - len;
        memcpy(p, cases[i], len);
        st = from_dump_status(p, len);
        ADF_CHECK_MSG(st == ADF_PARSE, "case \"%s\": status %s", cases[i],
                      adf_status_str(st));
        munmap(base, (size_t) pg * 2);
    }
}

/* A prime-power list with more than eight blocks: an under-allocation of the block array is
   visible once the blocks do not fit one word of bytes. */
ADF_TEST(new_prime_powers_many_blocks)
{
    ulong p[9] = {2, 3, 5, 7, 11, 13, 17, 19, 23};
    ulong e[9] = {1, 1, 1, 1, 1, 1, 1, 1, 1};
    adf_modctx_struct * ctx = NULL;
    int i;

    ADF_CHECK(adf_modctx_new_prime_powers(&ctx, p, e, 9) == ADF_OK);
    ADF_CHECK(adf_modctx_nblocks(ctx) == 9);
    for (i = 0; i < 9; i++)
        ADF_CHECK(adf_modctx_block(ctx, i) == p[i]);
    adf_modctx_free(ctx);
}

/* The first block of the descriptor is compared. */
ADF_TEST(matches_desc_compares_the_first_block)
{
    adf_ctx_desc_t d;
    adf_modctx_struct * ctx = NULL;
    ulong q[2] = {2, 3};

    ADF_CHECK(adf_modctx_new_blocks(&ctx, q, 2) == ADF_OK);
    adf_ctx_desc_init(&d);
    fmpz_set_ui(d.K, 6);
    d.k = 2;
    d.q = flint_malloc(2 * sizeof(ulong));
    d.q[0] = 2;
    d.q[1] = 3;
    ADF_CHECK(adf_modctx_matches_desc(ctx, &d) == 1);
    d.q[0] = 5;
    ADF_CHECK(adf_modctx_matches_desc(ctx, &d) == 0);
    adf_ctx_desc_clear(&d);
    adf_modctx_free(ctx);
}