/* tests/test_cap_vectors.c: the absolute cap against the JSON-lines vector oracle.

   adf_fball_cap is run against tests/ref/vectors/policies.jsonl, op "absolute_cap" (300 rows,
   tests/ref/gen_vectors.py function gen_policies, from tests/ref/adfref/policies.py function
   absolute_cap): this file is general ground truth, not owned by this lane, and is run
   completely (lanes/COMMON-C.md rule 2).

   No vector file combines a tight operation with the cap, so adf_fball_add_cap,
   adf_fball_sub_cap, adf_fball_mul_cap and adf_fball_mul_rat_cap are run against
   tests/ref/vectors/m1-cap/cap_ops.jsonl, generated by lanes/m1-cap/gen_vectors.py from the
   same Python reference (tests/ref/adfref/fball.py add/sub/mul/scale composed with
   tests/ref/adfref/policies.py absolute_cap); this file is owned by this lane and is also run
   completely. */

#include <stdio.h>
#include <string.h>

#include <adelefeld/scaled.h>

#include "support/jsonl.h"
#include "test_runner.h"

/* Read the integer in the JSON value into v (which is already initialised). */
static int
json_fmpz(fmpz_t v, const jsonl_value * j, jsonl_error_t * err)
{
    const char * text = jsonl_int_text(j, err);
    if (text == NULL)
        return 0;
    return fmpz_set_str(v, text, 10) == 0;
}

/* Build the ball {A,H,d} of a JSON object of the vector format, canonicalised. */
static int
json_ball(adf_fball_t x, const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value *jA, *jH, *jd;
    fmpz_t A, H, d;
    int ok;

    if (!jsonl_field(o, "A", &jA, err) || !jsonl_field(o, "H", &jH, err) ||
        !jsonl_field(o, "d", &jd, err))
        return 0;
    fmpz_init(A);
    fmpz_init(H);
    fmpz_init(d);
    ok = json_fmpz(A, jA, err) && json_fmpz(H, jH, err) && json_fmpz(d, jd, err) &&
         adf_fball_set_fmpz3(x, A, H, d) == ADF_OK;
    fmpz_clear(A);
    fmpz_clear(H);
    fmpz_clear(d);
    return ok;
}

/* Build the rational {num,den} of the vector format. */
static int
json_rat(adf_rat_t q, const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value *jn, *jd;
    fmpz_t n, d;
    int ok;

    if (!jsonl_field(o, "num", &jn, err) || !jsonl_field(o, "den", &jd, err))
        return 0;
    fmpz_init(n);
    fmpz_init(d);
    ok = json_fmpz(n, jn, err) && json_fmpz(d, jd, err);
    if (ok)
        fmpq_set_fmpz_frac(q->q, n, d);
    fmpz_clear(n);
    fmpz_clear(d);
    return ok;
}

/* Compare the fields of x with the canonical triple {A,H,d} of a JSON object. */
static int
ball_equals_json(const adf_fball_t x, const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value *jA, *jH, *jd;
    fmpz_t A, H, d;
    int ok;

    if (!jsonl_field(o, "A", &jA, err) || !jsonl_field(o, "H", &jH, err) ||
        !jsonl_field(o, "d", &jd, err))
        return 0;
    fmpz_init(A);
    fmpz_init(H);
    fmpz_init(d);
    ok = json_fmpz(A, jA, err) && json_fmpz(H, jH, err) && json_fmpz(d, jd, err) &&
         fmpz_equal(x->A, A) && fmpz_equal(x->H, H) && fmpz_equal(x->d, d);
    fmpz_clear(A);
    fmpz_clear(H);
    fmpz_clear(d);
    return ok;
}

/* ----------------------------------------------------- adf_fball_cap: policies.jsonl */

ADF_TEST(vectors_cap_absolute_cap)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    size_t i, n = 0;

    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/policies.jsonl", &f, &err) == 1, "%s",
                  jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * jball, * jC, * result;
        const char * op;
        size_t oplen;
        adf_fball_t x, y;
        adf_rat_t C;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op != NULL);
        if (op == NULL || strcmp(op, "absolute_cap") != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "ball", &jball, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "C", &jC, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "result", &result, &err) == 1);
        adf_fball_init(x);
        adf_fball_init(y);
        fmpq_init(C->q);
        ADF_CHECK(json_ball(x, jball, &err));
        ADF_CHECK(json_rat(C, jC, &err));
        ADF_CHECK(adf_fball_cap(y, x, C) == ADF_OK);
        ADF_CHECK(adf_fball_is_canonical(y));
        ADF_CHECK_MSG(ball_equals_json(y, result, &err), "policies.jsonl line %lu",
                      jsonl_line_of(rec));
        adf_fball_clear(x);
        adf_fball_clear(y);
        fmpq_clear(C->q);
    }
    jsonl_close(f);
    ADF_CHECK_MSG(n == 300, "expected 300 absolute_cap rows in policies.jsonl, found %lu",
                  (unsigned long) n);
}

/* ------------------------------------------------- the four combined operations: m1-cap */

static void
run_binary_cap(const char * path, const char * want_op,
                int (*op)(adf_fball_t, const adf_fball_t, const adf_fball_t, const adf_rat_t))
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    size_t i, n = 0;

    ADF_CHECK_MSG(jsonl_open(path, &f, &err) == 1, "%s", jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * ja, * jb, * jC, * result;
        const char * op_name;
        size_t oplen;
        adf_fball_t x, y, z;
        adf_rat_t C;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op_name = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op_name != NULL);
        if (op_name == NULL || strcmp(op_name, want_op) != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "b", &jb, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "C", &jC, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "result", &result, &err) == 1);
        adf_fball_init(x);
        adf_fball_init(y);
        adf_fball_init(z);
        fmpq_init(C->q);
        ADF_CHECK(json_ball(x, ja, &err));
        ADF_CHECK(json_ball(y, jb, &err));
        ADF_CHECK(json_rat(C, jC, &err));
        ADF_CHECK(op(z, x, y, C) == ADF_OK);
        ADF_CHECK(adf_fball_is_canonical(z));
        ADF_CHECK_MSG(ball_equals_json(z, result, &err), "%s line %lu", path,
                      jsonl_line_of(rec));
        adf_fball_clear(x);
        adf_fball_clear(y);
        adf_fball_clear(z);
        fmpq_clear(C->q);
    }
    jsonl_close(f);
    ADF_CHECK_MSG(n == 650, "expected 650 %s rows in %s, found %lu", want_op, path,
                  (unsigned long) n);
}

ADF_TEST(vectors_add_cap)
{
    run_binary_cap("tests/ref/vectors/m1-cap/cap_ops.jsonl", "add_cap", adf_fball_add_cap);
}

ADF_TEST(vectors_sub_cap)
{
    run_binary_cap("tests/ref/vectors/m1-cap/cap_ops.jsonl", "sub_cap", adf_fball_sub_cap);
}

ADF_TEST(vectors_mul_cap)
{
    run_binary_cap("tests/ref/vectors/m1-cap/cap_ops.jsonl", "mul_cap", adf_fball_mul_cap);
}

ADF_TEST(vectors_mul_rat_cap)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    size_t i, n = 0;

    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/m1-cap/cap_ops.jsonl", &f, &err) == 1, "%s",
                  jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * ja, * jq, * jC, * result;
        const char * op_name;
        size_t oplen;
        adf_fball_t x, y;
        adf_rat_t q, C;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op_name = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op_name != NULL);
        if (op_name == NULL || strcmp(op_name, "mul_rat_cap") != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "q", &jq, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "C", &jC, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "result", &result, &err) == 1);
        adf_fball_init(x);
        adf_fball_init(y);
        fmpq_init(q->q);
        fmpq_init(C->q);
        ADF_CHECK(json_ball(x, ja, &err));
        ADF_CHECK(json_rat(q, jq, &err));
        ADF_CHECK(json_rat(C, jC, &err));
        ADF_CHECK(adf_fball_mul_rat_cap(y, x, q, C) == ADF_OK);
        ADF_CHECK(adf_fball_is_canonical(y));
        ADF_CHECK_MSG(ball_equals_json(y, result, &err), "cap_ops.jsonl line %lu",
                      jsonl_line_of(rec));
        adf_fball_clear(x);
        adf_fball_clear(y);
        fmpq_clear(q->q);
        fmpq_clear(C->q);
    }
    jsonl_close(f);
    ADF_CHECK_MSG(n == 550, "expected 550 mul_rat_cap rows in cap_ops.jsonl, found %lu",
                  (unsigned long) n);
}
