/* tests/test_scaled_vectors.c: the scaled-residue policy against the JSON-lines vector oracles.

   Two files are run completely (lanes/COMMON-C.md rule 2):

   - tests/ref/vectors/policies.jsonl, the scaled rows: "convert_from_tight" (360 rows),
     "scaled_add" (300) and "scaled_mul" (300).  This is the general oracle, written from
     tests/ref/adfref/policies.py (convert_from_tight: Proposition 6(1) of
     docs/proofs/precision.md line 106 and policies Proposition 7 line 139; scaled_add:
     precision Proposition 5(1) line 99 with the exact-operand fallback of policies
     Proposition 8 line 159; scaled_mul: precision Proposition 5(2) and policies Proposition 9
     line 184).  The "absolute_cap" rows belong to tests/test_cap_vectors.c and are skipped here.

   - tests/ref/vectors/m1-scaled/scaled_ops.jsonl (1762 rows), the rows the general oracle does
     not have: neg, sub, scale, add_rat, mul with mixed exact operands, mul_tight
     (policies Proposition 10.3 line 200), set_context (policies Proposition 11 line 218) and
     to_fball.  Generated by lanes/m1-scaled/gen_scaled_vectors.py from the same Python
     reference plus the two formulas above, each cross-checked in the generator.

   Every scaled operand of a binary row is built in one context per modulus K, so the operands of
   a binary row share one context pointer (the shared-pointer rule of conventions 4.6 and SPEC
   4.4); a row whose operands would not share a pointer is not a row of these files.  Values are
   built only through the public API: a scaled value {s, u, K} is the ball s u + s K Zhat put
   through adf_scaled_set_fball, which stores exactly (s, u) by policies Lemma 5 (line 113). */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <adelefeld/scaled.h>

#include "support/jsonl.h"
#include "test_runner.h"

/* ---- small JSON helpers (the vector format of tests/ref/README.md) ---- */

static int
json_fmpz(fmpz_t v, const jsonl_value * j, jsonl_error_t * err)
{
    const char * text = jsonl_int_text(j, err);
    if (text == NULL)
        return 0;
    return fmpz_set_str(v, text, 10) == 0;
}

static int
json_rat(adf_rat_t q, const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value * jn, * jd;
    fmpz_t n, d;
    int ok;

    if (!jsonl_field(o, "num", &jn, err) || !jsonl_field(o, "den", &jd, err))
        return 0;
    fmpz_init(n);
    fmpz_init(d);
    ok = json_fmpz(n, jn, err) && json_fmpz(d, jd, err);
    if (ok)
        fmpq_set_fmpz_frac(q->q, n, d);
    fmpz_clear(n);
    fmpz_clear(d);
    return ok;
}

static int
json_ball(adf_fball_t x, const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value * jA, * jH, * jd;
    fmpz_t A, H, d;
    int ok;

    if (!jsonl_field(o, "A", &jA, err) || !jsonl_field(o, "H", &jH, err) ||
        !jsonl_field(o, "d", &jd, err))
        return 0;
    fmpz_init(A);
    fmpz_init(H);
    fmpz_init(d);
    ok = json_fmpz(A, jA, err) && json_fmpz(H, jH, err) && json_fmpz(d, jd, err) &&
         adf_fball_set_fmpz3(x, A, H, d) == ADF_OK;
    fmpz_clear(A);
    fmpz_clear(H);
    fmpz_clear(d);
    return ok;
}

static int
ball_equals_json(const adf_fball_t x, const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value * jA, * jH, * jd;
    fmpz_t A, H, d;
    int ok;

    if (!jsonl_field(o, "A", &jA, err) || !jsonl_field(o, "H", &jH, err) ||
        !jsonl_field(o, "d", &jd, err))
        return 0;
    fmpz_init(A);
    fmpz_init(H);
    fmpz_init(d);
    ok = json_fmpz(A, jA, err) && json_fmpz(H, jH, err) && json_fmpz(d, jd, err) &&
         fmpz_equal(x->A, A) && fmpz_equal(x->H, H) && fmpz_equal(x->d, d);
    fmpz_clear(A);
    fmpz_clear(H);
    fmpz_clear(d);
    return ok;
}

/* ---- one context per modulus, shared by every operand that names that modulus ---- */

#define CTX_CACHE_MAX 32

typedef struct
{
    const adf_modctx_struct * ctx[CTX_CACHE_MAX];
    char key[CTX_CACHE_MAX][32];
    size_t n;
} ctx_cache;

static void
cache_init(ctx_cache * c)
{
    c->n = 0;
}

/* The context of modulus ktext (the decimal literal of the vector); one pointer per modulus, so
   operands of one modulus share a pointer. */
static const adf_modctx_struct *
cache_get(ctx_cache * c, const char * ktext)
{
    size_t i;
    fmpz_t K;
    adf_modctx_struct * fresh = NULL;

    for (i = 0; i < c->n; i++)
        if (strcmp(c->key[i], ktext) == 0)
            return c->ctx[i];
    ADF_CHECK(c->n < CTX_CACHE_MAX);
    ADF_CHECK(strlen(ktext) < sizeof(c->key[0]));
    fmpz_init(K);
    if (fmpz_set_str(K, ktext, 10) != 0 || fmpz_sgn(K) < 1 ||
        adf_modctx_new_fmpz(&fresh, K) != ADF_OK)
    {
        fmpz_clear(K);
        ADF_CHECK(0);
        return NULL;
    }
    fmpz_clear(K);
    strcpy(c->key[c->n], ktext);
    c->ctx[c->n] = fresh;
    return c->ctx[c->n++];
}

static void
cache_clear(ctx_cache * c)
{
    size_t i;
    for (i = 0; i < c->n; i++)
        adf_modctx_free((adf_modctx_struct *) c->ctx[i]);
    c->n = 0;
}

/* ---- policy values: {"exact": {num,den}} or {"s": {num,den}, "u": U, "K": K} ---- */

/* The "K" member of a value object as its literal, or NULL for an exact value. */
static const char *
value_Ktext(const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value * jK;

    if (!jsonl_field(o, "K", &jK, err))
    {
        err->message[0] = '\0'; /* a value without "K" is exact, not an error */
        return NULL;
    }
    return jsonl_int_text(jK, err);
}

/* Build the value of o in ctx: exact values through adf_scaled_set_rat, scaled values as the
   ball s u + s K Zhat through adf_scaled_set_fball (policies Lemma 5: the data (s, u) are those
   of the set, so this stores exactly the row's s and u). */
static int
build_value(adf_scaled_t x, const jsonl_value * o, const adf_modctx_struct * ctx,
            jsonl_error_t * err)
{
    const jsonl_value * js, * ju, * je;
    adf_rat_t q, c, r;
    adf_fball_t b;
    int ok = 1;

    if (jsonl_field(o, "exact", &je, err))
    {
        adf_rat_init(q);
        ok = json_rat(q, je, err);
        if (ok)
            adf_scaled_set_rat(x, q, ctx);
        adf_rat_clear(q);
        return ok;
    }
    err->message[0] = '\0';
    if (!jsonl_field(o, "s", &js, err) || !jsonl_field(o, "u", &ju, err))
        return 0;
    adf_rat_init(q);
    adf_rat_init(c);
    adf_rat_init(r);
    adf_fball_init(b);
    ok = json_rat(q, js, err);
    if (ok)
    {
        fmpz_t u, t;
        fmpz_init(u);
        fmpz_init(t);
        ok = json_fmpz(u, ju, err);
        if (ok)
        {
            fmpq_mul_fmpz(c->q, q->q, u);           /* c = s u */
            adf_modctx_get_modulus(t, ctx);
            fmpq_mul_fmpz(r->q, q->q, t);           /* radius r = s K */
            ok = adf_fball_set_center_radius(b, c, r) == ADF_OK &&
                 adf_scaled_set_fball(x, NULL, b, ctx) == ADF_OK;
        }
        fmpz_clear(u);
        fmpz_clear(t);
    }
    adf_rat_clear(q);
    adf_rat_clear(c);
    adf_rat_clear(r);
    adf_fball_clear(b);
    return ok;
}

/* 1 if x holds exactly the value of o: same exact tag, same rational data, same modulus. */
static int
value_equals_json(const adf_scaled_t x, const jsonl_value * o, jsonl_error_t * err)
{
    const jsonl_value * je, * js, * ju, * jK;
    adf_rat_t q;
    fmpz_t u, Km, Kj;
    int ok = 0;

    adf_rat_init(q);
    fmpz_init(u);
    fmpz_init(Km);
    fmpz_init(Kj);
    if (jsonl_field(o, "exact", &je, err))
    {
        ok = json_rat(q, je, err) && adf_scaled_is_exact(x) && fmpq_equal(q->q, x->s) &&
             fmpz_is_zero(x->u);
    }
    else
    {
        err->message[0] = '\0';
        if (jsonl_field(o, "s", &js, err) && jsonl_field(o, "u", &ju, err) &&
            jsonl_field(o, "K", &jK, err))
        {
            adf_modctx_get_modulus(Km, x->mctx);
            ok = json_rat(q, js, err) && json_fmpz(u, ju, err) && json_fmpz(Kj, jK, err) &&
                 !adf_scaled_is_exact(x) && fmpq_equal(q->q, x->s) && fmpz_equal(u, x->u) &&
                 fmpz_equal(Km, Kj);
        }
    }
    adf_rat_clear(q);
    fmpz_clear(u);
    fmpz_clear(Km);
    fmpz_clear(Kj);
    return ok;
}

/* The shared context of a binary row: the K of the scaled operand (both scaled operands must
   name the same K), or the context of modulus 1 for two exact operands. */
static const adf_modctx_struct *
binary_ctx(ctx_cache * c, const jsonl_value * ja, const jsonl_value * jb, jsonl_error_t * err)
{
    const char * ka = value_Ktext(ja, err);
    const char * kb = value_Ktext(jb, err);

    if (ka != NULL && kb != NULL && strcmp(ka, kb) != 0)
        return NULL;
    return cache_get(c, ka != NULL ? ka : (kb != NULL ? kb : "1"));
}

/* --------------------------------------- policies.jsonl: convert_from_tight (360 rows) ---- */

ADF_TEST(vectors_policies_convert_from_tight)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    ctx_cache cache;
    size_t i, n = 0;

    cache_init(&cache);
    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/policies.jsonl", &f, &err) == 1, "%s",
                  jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * jball, * jK, * jval, * jlost;
        const char * op;
        size_t oplen;
        const adf_modctx_struct * ctx;
        adf_fball_t x;
        adf_scaled_t y;
        int lost = -1, want_lost;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op != NULL);
        if (op == NULL || strcmp(op, "convert_from_tight") != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "ball", &jball, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "K", &jK, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "value", &jval, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "lost", &jlost, &err) == 1);
        ADF_CHECK(jsonl_bool(jlost, &want_lost, &err) == 1);
        ctx = cache_get(&cache, jsonl_int_text(jK, &err));
        adf_fball_init(x);
        adf_scaled_init(y, ctx);
        ADF_CHECK(json_ball(x, jball, &err));
        ADF_CHECK(adf_scaled_set_fball(y, &lost, x, ctx) == ADF_OK);
        ADF_CHECK(adf_scaled_is_canonical(y));
        ADF_CHECK_MSG(lost == want_lost, "policies.jsonl line %lu: lost = %d, want %d",
                      jsonl_line_of(rec), lost, want_lost);
        ADF_CHECK_MSG(value_equals_json(y, jval, &err), "policies.jsonl line %lu",
                      jsonl_line_of(rec));
        adf_fball_clear(x);
        adf_scaled_clear(y);
    }
    jsonl_close(f);
    cache_clear(&cache);
    ADF_CHECK_MSG(n == 360, "expected 360 convert_from_tight rows in policies.jsonl, found %lu",
                  (unsigned long) n);
}

/* ------------------------------------------ policies.jsonl: scaled_add and scaled_mul ---- */

static void
run_policies_binary(const char * want_op, int is_mul, size_t want_rows)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    ctx_cache cache;
    size_t i, n = 0;

    cache_init(&cache);
    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/policies.jsonl", &f, &err) == 1, "%s",
                  jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * ja, * jb, * jres;
        const char * op;
        size_t oplen;
        const adf_modctx_struct * ctx;
        adf_scaled_t x, y, z;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op != NULL);
        if (op == NULL || strcmp(op, want_op) != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "b", &jb, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "result", &jres, &err) == 1);
        ctx = binary_ctx(&cache, ja, jb, &err);
        ADF_CHECK(ctx != NULL);
        adf_scaled_init(x, ctx);
        adf_scaled_init(y, ctx);
        adf_scaled_init(z, ctx);
        ADF_CHECK(build_value(x, ja, ctx, &err));
        ADF_CHECK(build_value(y, jb, ctx, &err));
        ADF_CHECK((is_mul ? adf_scaled_mul(z, x, y) : adf_scaled_add(z, x, y)) == ADF_OK);
        ADF_CHECK(adf_scaled_is_canonical(z));
        ADF_CHECK(adf_scaled_context(z) == ctx);
        ADF_CHECK_MSG(value_equals_json(z, jres, &err), "%s line %lu", want_op,
                      jsonl_line_of(rec));
        adf_scaled_clear(x);
        adf_scaled_clear(y);
        adf_scaled_clear(z);
    }
    jsonl_close(f);
    cache_clear(&cache);
    ADF_CHECK_MSG(n == want_rows, "expected %lu %s rows in policies.jsonl, found %lu",
                  (unsigned long) want_rows, want_op, (unsigned long) n);
}

ADF_TEST(vectors_policies_scaled_add)
{
    run_policies_binary("scaled_add", 0, 300);
}

ADF_TEST(vectors_policies_scaled_mul)
{
    run_policies_binary("scaled_mul", 1, 300);
}

/* --------------------------------------- scaled_ops.jsonl: rows with one result value ---- */

/* Rows of the shape {op, a, [q], result}: neg, scale, sub, mul_exact, mul_tight. */
static void
run_lane_row(const char * path, const char * want_op, int kind, size_t want_rows)
{
    /* kind: 0 = unary neg, 1 = scale (a, q), 2 = binary (a, b) */
    jsonl_error_t err;
    jsonl_file * f = NULL;
    ctx_cache cache;
    size_t i, n = 0;

    cache_init(&cache);
    ADF_CHECK_MSG(jsonl_open(path, &f, &err) == 1, "%s", jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * ja, * jb, * jq, * jres;
        const char * op;
        size_t oplen;
        const adf_modctx_struct * ctx;
        adf_scaled_t x, y, z;
        adf_rat_t q;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op != NULL);
        if (op == NULL || strcmp(op, want_op) != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "result", &jres, &err) == 1);
        if (kind == 2)
        {
            ADF_CHECK(jsonl_field(rec, "b", &jb, &err) == 1);
            ctx = binary_ctx(&cache, ja, jb, &err);
        }
        else
            ctx = cache_get(&cache, value_Ktext(ja, &err) != NULL ? value_Ktext(ja, &err) : "1");
        ADF_CHECK(ctx != NULL);
        adf_scaled_init(x, ctx);
        adf_scaled_init(y, ctx);
        adf_scaled_init(z, ctx);
        adf_rat_init(q);
        ADF_CHECK(build_value(x, ja, ctx, &err));
        if (kind == 0)
        {
            adf_scaled_neg(y, x);
            ADF_CHECK(value_equals_json(y, jres, &err));
        }
        else if (kind == 1)
        {
            ADF_CHECK(jsonl_field(rec, "q", &jq, &err) == 1);
            ADF_CHECK(json_rat(q, jq, &err));
            adf_scaled_mul_rat(y, x, q);
            ADF_CHECK(adf_scaled_context(y) == ctx);
            ADF_CHECK(value_equals_json(y, jres, &err));
        }
        else
        {
            ADF_CHECK(build_value(y, jb, ctx, &err));
            if (strcmp(want_op, "sub") == 0)
                ADF_CHECK(adf_scaled_sub(z, x, y) == ADF_OK);
            else if (strcmp(want_op, "mul_exact") == 0)
                ADF_CHECK(adf_scaled_mul(z, x, y) == ADF_OK);
            else
                ADF_CHECK(adf_scaled_mul_tight(z, x, y) == ADF_OK);
            ADF_CHECK(adf_scaled_context(z) == ctx);
            ADF_CHECK(value_equals_json(z, jres, &err));
        }
        ADF_CHECK(adf_scaled_is_canonical(kind == 0 || kind == 1 ? y : z));
        adf_scaled_clear(x);
        adf_scaled_clear(y);
        adf_scaled_clear(z);
        adf_rat_clear(q);
    }
    jsonl_close(f);
    cache_clear(&cache);
    ADF_CHECK_MSG(n == want_rows, "expected %lu %s rows in %s, found %lu",
                  (unsigned long) want_rows, want_op, path, (unsigned long) n);
}

ADF_TEST(vectors_lane_neg)
{
    run_lane_row("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", "neg", 0, 129);
}

ADF_TEST(vectors_lane_scale)
{
    run_lane_row("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", "scale", 1, 205);
}

ADF_TEST(vectors_lane_sub)
{
    run_lane_row("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", "sub", 2, 263);
}

ADF_TEST(vectors_lane_mul_exact)
{
    run_lane_row("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", "mul_exact", 2, 223);
}

ADF_TEST(vectors_lane_mul_tight)
{
    run_lane_row("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", "mul_tight", 2, 283);
}

/* ---------------------------------------------- scaled_ops.jsonl: add_rat (value + lost) -- */

ADF_TEST(vectors_lane_add_rat)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    ctx_cache cache;
    size_t i, n = 0;

    cache_init(&cache);
    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", &f, &err) == 1,
                  "%s", jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * ja, * jq, * jval, * jlost;
        const char * op;
        size_t oplen;
        const adf_modctx_struct * ctx;
        adf_scaled_t x, y;
        adf_rat_t q;
        int lost = -1, want_lost;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op != NULL);
        if (op == NULL || strcmp(op, "add_rat") != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "q", &jq, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "value", &jval, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "lost", &jlost, &err) == 1);
        ADF_CHECK(jsonl_bool(jlost, &want_lost, &err) == 1);
        ctx = cache_get(&cache, value_Ktext(ja, &err) != NULL ? value_Ktext(ja, &err) : "1");
        adf_scaled_init(x, ctx);
        adf_scaled_init(y, ctx);
        adf_rat_init(q);
        ADF_CHECK(build_value(x, ja, ctx, &err));
        ADF_CHECK(json_rat(q, jq, &err));
        adf_scaled_add_rat(y, &lost, x, q);
        ADF_CHECK(adf_scaled_is_canonical(y));
        ADF_CHECK(adf_scaled_context(y) == ctx);
        ADF_CHECK_MSG(lost == want_lost, "add_rat line %lu: lost = %d, want %d",
                      jsonl_line_of(rec), lost, want_lost);
        ADF_CHECK_MSG(value_equals_json(y, jval, &err), "add_rat line %lu",
                      jsonl_line_of(rec));
        adf_scaled_clear(x);
        adf_scaled_clear(y);
        adf_rat_clear(q);
    }
    jsonl_close(f);
    cache_clear(&cache);
    ADF_CHECK_MSG(n == 245, "expected 245 add_rat rows, found %lu", (unsigned long) n);
}

/* ------------------------------------------ scaled_ops.jsonl: set_context (value + lost) -- */

ADF_TEST(vectors_lane_set_context)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    ctx_cache cache;
    size_t i, n = 0;

    cache_init(&cache);
    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", &f, &err) == 1,
                  "%s", jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * ja, * jK2, * jval, * jlost;
        const char * op, * k2text, * ktext;
        size_t oplen;
        const adf_modctx_struct * ctx, * ctx2;
        adf_scaled_t x, y;
        int lost = -1, want_lost;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op != NULL);
        if (op == NULL || strcmp(op, "set_context") != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "K2", &jK2, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "value", &jval, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "lost", &jlost, &err) == 1);
        ADF_CHECK(jsonl_bool(jlost, &want_lost, &err) == 1);
        k2text = jsonl_int_text(jK2, &err);
        ADF_CHECK(k2text != NULL);
        ktext = value_Ktext(ja, &err);
        ctx2 = cache_get(&cache, k2text);
        /* an exact input has no K of its own; its context does not enter the formula */
        ctx = cache_get(&cache, ktext != NULL ? ktext : k2text);
        adf_scaled_init(x, ctx);
        adf_scaled_init(y, ctx2);
        ADF_CHECK(build_value(x, ja, ctx, &err));
        ADF_CHECK(adf_scaled_set_context(y, &lost, x, ctx2) == ADF_OK);
        ADF_CHECK(adf_scaled_is_canonical(y));
        ADF_CHECK(adf_scaled_context(y) == ctx2);
        ADF_CHECK_MSG(lost == want_lost, "set_context line %lu: lost = %d, want %d",
                      jsonl_line_of(rec), lost, want_lost);
        ADF_CHECK_MSG(value_equals_json(y, jval, &err), "set_context line %lu",
                      jsonl_line_of(rec));
        adf_scaled_clear(x);
        adf_scaled_clear(y);
    }
    jsonl_close(f);
    cache_clear(&cache);
    ADF_CHECK_MSG(n == 285, "expected 285 set_context rows, found %lu", (unsigned long) n);
}

/* --------------------------------------------------- scaled_ops.jsonl: to_fball (a ball) -- */

ADF_TEST(vectors_lane_to_fball)
{
    jsonl_error_t err;
    jsonl_file * f = NULL;
    ctx_cache cache;
    size_t i, n = 0;

    cache_init(&cache);
    ADF_CHECK_MSG(jsonl_open("tests/ref/vectors/m1-scaled/scaled_ops.jsonl", &f, &err) == 1,
                  "%s", jsonl_error_message(&err));
    if (f == NULL)
        return;
    for (i = 0; i < jsonl_count(f); i++)
    {
        const jsonl_value * rec = jsonl_record(f, i);
        const jsonl_value * opv, * ja, * jres;
        const char * op;
        size_t oplen;
        const adf_modctx_struct * ctx;
        adf_scaled_t x;
        adf_fball_t y;

        ADF_CHECK(jsonl_field(rec, "op", &opv, &err) == 1);
        op = jsonl_string(opv, &oplen, &err);
        ADF_CHECK(op != NULL);
        if (op == NULL || strcmp(op, "to_fball") != 0)
            continue;
        n++;

        ADF_CHECK(jsonl_field(rec, "a", &ja, &err) == 1);
        ADF_CHECK(jsonl_field(rec, "result", &jres, &err) == 1);
        ctx = cache_get(&cache, value_Ktext(ja, &err) != NULL ? value_Ktext(ja, &err) : "1");
        adf_scaled_init(x, ctx);
        adf_fball_init(y);
        ADF_CHECK(build_value(x, ja, ctx, &err));
        adf_scaled_get_fball(y, x);
        ADF_CHECK(adf_fball_is_canonical(y));
        ADF_CHECK_MSG(ball_equals_json(y, jres, &err), "to_fball line %lu",
                      jsonl_line_of(rec));
        adf_scaled_clear(x);
        adf_fball_clear(y);
    }
    jsonl_close(f);
    cache_clear(&cache);
    ADF_CHECK_MSG(n == 129, "expected 129 to_fball rows, found %lu", (unsigned long) n);
}
