#!/bin/sh
# gen_hostile.sh: write the hostile inputs of the driver test into build/driver/.
# Run from the repository root (tests/test_driver.sh does it):
#
#   sh tests/driver/gen_hostile.sh
#
# Only generated bytes go to build/; the expected outputs are the files of
# tests/driver/hostile/.  Nothing is written into the working tree.
#
# Inputs:
#   h1_nul.cmd            three lines, a NUL byte in two of them
#   h2_high.cmd           the bytes 128 to 255, in an operand and in an operation word
#   h3_line_65536.cmd     one line of exactly 65536 bytes
#   h4_line_65537.cmd     one line of 65537 bytes, a second command inside it, then a line
#   h5_no_final_newline.cmd  one command without a final newline
#   h6_empty.cmd          an empty file
#   h7_many_lines.cmd     100000 lines, with the expected output beside it
#   h9_settings_ws.cmd    blanks, tabs and a CR around the number of a setting
#
# The line limit of the driver is 65536 bytes (README of tools/adf).

set -u
OUT=build/driver
mkdir -p "$OUT" || exit 1

# h1: a NUL byte inside a line.  printf with \000 writes one NUL byte.
{
    printf 'show 7/3\000\n'
    printf 'show 7/3\n'
    printf 'add 7/3 with 1\000/2\n'
} > "$OUT/h1_nul.cmd"

# h2: the bytes 128 to 255, twice (128 of them, 0x80 to 0xFF).
{
    printf 'show '
    awk 'BEGIN { for (i = 128; i < 256; i++) printf "%c", i }'
    printf '\n'
    awk 'BEGIN { for (i = 128; i < 256; i++) printf "%c", i }'
    printf ' 7/3\n'
    printf 'type '
    awk 'BEGIN { for (i = 128; i < 256; i++) printf "%c", i }'
    printf '\n'
    printf 'add 7/3 with '
    awk 'BEGIN { for (i = 128; i < 256; i++) printf "%c", i }'
    printf '\n'
} > "$OUT/h2_high.cmd"

# h3: "show 7/3" is 8 bytes; 65528 spaces bring the line to exactly 65536 bytes.
{
    printf 'show 7/3'
    awk 'BEGIN { for (i = 0; i < 65528; i++) printf " " }'
    printf '\n'
} > "$OUT/h3_line_65536.cmd"

# h4: 65537 bytes on one line: "show 7/3" (8), 65521 spaces, a second command of the same
# line (8), and the newline.  The whole line is too long, so the second command inside it
# is not run.
{
    printf 'show 7/3'
    awk 'BEGIN { for (i = 0; i < 65521; i++) printf " " }'
    printf 'show 1/2\n'
    printf 'show 7/3\n'
} > "$OUT/h4_line_65537.cmd"

# h5: no final newline.
printf 'show 7/3' > "$OUT/h5_no_final_newline.cmd"

# h6: an empty file.
: > "$OUT/h6_empty.cmd"

# h7: 100000 lines, and the expected output beside them.
awk 'BEGIN { for (i = 0; i < 100000; i++) print "show 7/3" }' > "$OUT/h7_many_lines.cmd"
awk 'BEGIN { for (i = 0; i < 100000; i++) print "7/3" }' > "$OUT/h7_many_lines.out"

# h9: the number of a setting with whitespace around it.  The whitespace of the value form
# (conventions 8.2) is the space, TAB, LF and CR, and it may stand before the first token and
# after the last one; tools/adf/README.md says a command may be written with spaces around it.
# A CRLF script must therefore run every setting line, and so must a line with trailing
# blanks.  A setting writes no line, so only the value command and the two refusals of the
# last lines are in the expected output.
{
    printf 'prec 64 \r\n'       # a trailing blank and a CR
    printf 'prec\t64\t\n'       # tabs on both sides of the number
    printf 'prec  64\n'         # blanks before the number
    printf 'digits 20\r\n'      # a CR only
    printf 'show 7/3\r\n'       # the value command of a CRLF script
    printf 'prec 0x40\n'        # not a decimal integer
    printf 'digits 2 0\n'       # a blank inside the number
    printf 'prec 64 \t \n'      # blanks and a tab after the number
    printf 'prec  100001 \n'    # above ADF_PRINT_EXP_MAX: error: LIMIT
} > "$OUT/h9_settings_ws.cmd"

# The lengths of the lines of h3 and h4 are part of the test, so they are reported: the
# length of a line is what stands before its newline.
awk 'FNR == 1 && FILENAME ~ /h3_/ { print FILENAME ": the first line is " length($0) " bytes" }' \
    "$OUT/h3_line_65536.cmd"
awk 'FNR == 1 && FILENAME ~ /h4_/ { print FILENAME ": the first line is " length($0) " bytes" }' \
    "$OUT/h4_line_65537.cmd"
wc -c "$OUT"/h*.cmd | sed 's|build/driver/||'
