#!/usr/bin/env python3
"""Oracle for fball_fuzz.c. Exact arithmetic with fractions.Fraction; no code under review.

A ball is (A + H Zhat)/d = a + N Zhat, a = A/d, N = H/d. Its rational points are a + N Z
(precision.md Lemma 1). The oracle:
- canonical triple: by Lemma 5.2 of conventions (d0 = lcm(den a, den N), H0 = N d0,
  A0 = a d0 mod H0; N = 0: lowest terms), not the gcd route of fball.c;
- sum, difference, product, scalar product: the radius is the non-negative generator R of the
  subgroup of Q generated by the differences {u v - c : u, v rational points near the centres}
  (enumerated over a 5 x 5 grid of lattice points, which generates the same subgroup as all of them),
  the centre is the image of the centres. Enclosure: every enumerated result point lies in the
  output ball (membership by Lemma 1: (p - c)/R integral). Tightness: the output radius equals R;
- predicates: by enumeration of lattice points. x inside y iff a in y and a + N in y (the rational
  points of x are generated by those two, and a ball is the closure of its rational points);
  overlap iff some lattice point of x lies in y, searched over one full period of k;
  equal iff inside both ways; compare from the three;
- accessors: centre in [0, N) (or the point), radius N, den d0, volume 1/N (0 if exact), v_p(N).
"""
import sys
from fractions import Fraction
from math import gcd, lcm


def canon(a, N):
    if N == 0:
        return (a.numerator, 0, a.denominator)
    d0 = lcm(a.denominator, N.denominator)
    H0 = int(N * d0)
    A0 = int(a * d0) % H0
    return (A0, H0, d0)


def cr(t):
    A, H, d = t
    return Fraction(A, d), Fraction(H, d)


def qgcd(vals):
    """Non-negative generator of the subgroup of Q generated by vals."""
    vals = [Fraction(v) for v in vals if v != 0]
    if not vals:
        return Fraction(0)
    D = 1
    for v in vals:
        D = lcm(D, v.denominator)
    g = 0
    for v in vals:
        g = gcd(g, int(v * D))
    return Fraction(g, D)


def member(p, a, N):
    if N == 0:
        return p == a
    return ((p - a) / N).denominator == 1


def points(a, N, K=2):
    if N == 0:
        return [a]
    return [a + N * k for k in range(-K, K + 1)]


def ball_image(pairs, c):
    R = qgcd([p - c for p in pairs])
    return c, R


def inside(x, y):
    a, N = x
    b, M = y
    if M == 0:
        return N == 0 and a == b
    return member(a, b, M) and member(a + N, b, M)


def overlaps(x, y):
    a, N = x
    b, M = y
    if N == 0 and M == 0:
        return a == b
    if N == 0:
        return member(a, b, M)
    if M == 0:
        return member(b, a, N)
    # lattice points a + N k; membership in b + M Z is periodic in k with the period
    # den(N/M) (N k / M is an integer exactly when den(N/M) divides k): search one period.
    per = (N / M).denominator
    if per > 20000:
        # large operands: Proposition 3(2) with the gcd of this file (not the enumeration)
        return member(a - b, Fraction(0), qgcd([N, M]))
    return any(member(a + N * k, b, M) for k in range(per))


def vp(x, p):
    if x == 0:
        return None
    n, d = x.numerator, x.denominator
    v = 0
    while n % p == 0:
        n //= p
        v += 1
    while d % p == 0:
        d //= p
        v -= 1
    return v


def parse(line):
    f = {}
    for part in line.split(" ; "):
        toks = part.split()
        f[toks[0]] = toks[1:]
    return f


def tri(toks):
    return tuple(int(t) for t in toks)


def main():
    n = 0
    fails = []
    stats = {"exact_x": 0, "exact_y": 0, "ov": 0, "eq": 0, "cxy": 0, "neg_ctr": 0}
    alias_line = None
    for line in sys.stdin:
        line = line.rstrip("\n")
        if line.startswith("#alias_failures"):
            alias_line = line
            continue
        if line.startswith("#"):
            fails.append((line, ["aliasing"]))
            continue
        n += 1
        f = parse(line)
        bad = []
        rx = tri(f["x"][:3]); sx = int(f["x"][3]); x3 = tri(f["x"][4:])
        ry = tri(f["y"][:3]); sy = int(f["y"][3]); y3 = tri(f["y"][4:])
        q = Fraction(f["q"][0])
        # canonicalisation of the raw triples
        for raw, s, got, nm in ((rx, sx, x3, "x"), (ry, sy, y3, "y")):
            A, H, d = raw
            if s != 0:
                bad.append("set_fmpz3 %s status %d" % (nm, s))
                continue
            a, N = Fraction(A, d), Fraction(H, abs(d))
            if got != canon(a, N):
                bad.append("canon %s: %s expected %s" % (nm, got, canon(a, N)))
        x = cr(x3)
        y = cr(y3)
        a, N = x
        b, M = y
        stats["exact_x"] += N == 0
        stats["exact_y"] += M == 0
        stats["neg_ctr"] += (a < 0) or (b < 0)
        px, py = points(a, N), points(b, M)
        # sum, difference, product, square
        for op, fn, c, ys in (("add", lambda u, v: u + v, a + b, py),
                              ("sub", lambda u, v: u - v, a - b, py),
                              ("mul", lambda u, v: u * v, a * b, py),
                              ("sq", lambda u, v: u * v, a * a, px)):
            res = [fn(u, v) for u in px for v in ys]
            c0, R = ball_image(res, c)
            got = tri(f[op])
            if got != canon(c0, R):
                bad.append("%s: %s expected %s" % (op, got, canon(c0, R)))
            gc, gN = cr(got)
            for p in res:
                if not member(p, gc, gN):
                    bad.append("%s: ENCLOSURE %s not in output" % (op, p))
                    break
        # neg
        if tri(f["neg"]) != canon(-a, N):
            bad.append("neg")
        # scalar product and quotient
        res = [q * u for u in px]
        c0, R = ball_image(res, q * a)
        if tri(f["mulq"]) != canon(c0, R):
            bad.append("mulq: %s expected %s" % (tri(f["mulq"]), canon(c0, R)))
        st = int(f["divq"][0])
        if q == 0:
            if st != 6 or tri(f["divq"][1:]) != (-12345, 0, 1):
                bad.append("divq by 0: status %d output %s" % (st, f["divq"][1:]))
        else:
            res = [u / q for u in px]
            c0, R = ball_image(res, a / q)
            if st != 0 or tri(f["divq"][1:]) != canon(c0, R):
                bad.append("divq: %s expected %s" % (f["divq"], canon(c0, R)))
        # predicates
        cxy, cyx = inside(x, y), inside(y, x)
        ov = overlaps(x, y)
        eq = cxy and cyx
        stats["ov"] += ov
        stats["eq"] += eq
        stats["cxy"] += cxy
        for nm, want in (("eq", eq), ("ov", ov), ("cxy", cxy), ("cyx", cyx),
                         ("crq", member(q, a, N))):
            if int(f[nm][0]) != int(want):
                bad.append("%s: got %s expected %d" % (nm, f[nm][0], want))
        if N == 0 and M == 0 and a == b:
            cmp = 0
        elif not ov:
            cmp = 1
        else:
            cmp = 2
        if int(f["cmp"][0]) != cmp:
            bad.append("cmp: got %s expected %d" % (f["cmp"][0], cmp))
        # accessors
        A0, H0, d0 = canon(a, N)
        if Fraction(f["ctr"][0]) != Fraction(A0, d0):
            bad.append("ctr")
        if N > 0 and not (0 <= Fraction(f["ctr"][0]) < N):
            bad.append("ctr not in [0, N)")
        if Fraction(f["rad"][0]) != N:
            bad.append("rad")
        if int(f["den"][0]) != d0:
            bad.append("den")
        if Fraction(f["vol"][0]) != (0 if N == 0 else 1 / N):
            bad.append("vol")
        for p, key in ((2, "prec2"), (3, "prec3")):
            s, e = int(f[key][0]), int(f[key][1])
            if N == 0:
                if s != 7 or e != 777:
                    bad.append("%s exact: %s" % (key, f[key]))
            elif s != 0 or e != vp(N, p):
                bad.append("%s: %s expected %s" % (key, f[key], vp(N, p)))
        if int(f["canon"][0]) != 1:
            bad.append("an output is not canonical")
        if int(f["exact"][0]) != int(N == 0):
            bad.append("is_exact")
        if bad:
            fails.append((line[:400], bad))
    print("cases:", n, "stats:", stats)
    print(alias_line)
    print("failures:", len(fails))
    for l, b in fails[:10]:
        print("  ", b[:5], "\n     ", l)


main()
