#!/usr/bin/env python3
"""Exact checks for docs/seams.md (work package 0.6).

Two instances of the restricted product are tested against the version-1 interface for Q:

  K = Q(sqrt(-5)), O_K = Z[w] with w^2 = -5 (class number 2, P = (2, 1 + w) not principal);
  F = F_3(T) with its place at infinity (s = 1/T is a uniformiser there).

Number field part. An element x + y w of K is a pair (x, y) of Fractions. A Z-lattice of rank 2 in K (a fractional
ideal, or a radius) is stored canonically as (d, a, b, c): the lattice (1/d) (Z (a, 0) + Z (b, c)) in the
coordinates of the basis (1, w), with a, c > 0, 0 <= b < a, and d the least positive integer with d L inside
Z^2. The Hermite normal form is computed here from scratch (no library), so every lattice identity below is an
independent exact computation. Since O_K = Z[w] has Z-basis (1, w), the profinite completion Ohat = O_K (x) Zhat
is Zhat^2 in the same coordinates; a finite ball a + I Ohat is a coset of the Zhat-span of a Z-basis of I.

Function field part. Polynomials over F_3 are python-flint nmod_poly. A rational function is a reduced pair
(numerator, monic denominator). The expansion at infinity is in s = 1/T.

Each check prints one line with its counts. The script exits non-zero if any check fails. The "mutant" lines apply
a deliberately wrong rule and require that the check detects it (so the check is not vacuous).
"""
from fractions import Fraction as Fr
from math import gcd, isqrt
import random
import sys

FAILURES = []


def report(name, ok, detail):
    print(f"{'PASS' if ok else 'FAIL'}  {name}: {detail}")
    if not ok:
        FAILURES.append(name)


def lcm(a, b):
    return a * b // gcd(a, b) if a and b else 0


# ==================================================================================================================
# Part K: K = Q(sqrt(-5))
# ==================================================================================================================

W = (Fr(0), Fr(1))
ONE = (Fr(1), Fr(0))


def el(x, y=0):
    return (Fr(x), Fr(y))


def eadd(a, b):
    return (a[0] + b[0], a[1] + b[1])


def esub(a, b):
    return (a[0] - b[0], a[1] - b[1])


def emul(a, b):
    return (a[0] * b[0] - 5 * a[1] * b[1], a[0] * b[1] + a[1] * b[0])


def econj(a):
    return (a[0], -a[1])


def enorm(a):
    """N_{K/Q}(x + y w) = x^2 + 5 y^2."""
    return a[0] * a[0] + 5 * a[1] * a[1]


def etrace(a):
    return 2 * a[0]


def einv(a):
    n = enorm(a)
    c = econj(a)
    return (c[0] / n, c[1] / n)


def iszero(a):
    return a[0] == 0 and a[1] == 0


def hnf(ivecs):
    """HNF of a full-rank lattice in Z^2 spanned by integer vectors: returns (a, b, c) with the lattice equal to
    Z (a, 0) + Z (b, c), a, c > 0, 0 <= b < a. Raises if the vectors do not span a lattice of rank 2."""
    rows = [[x, y] for (x, y) in ivecs if (x, y) != (0, 0)]
    while True:
        nz = [r for r in rows if r[1] != 0]
        if len(nz) <= 1:
            break
        piv = min(nz, key=lambda r: abs(r[1]))
        for r in rows:
            if r is not piv and r[1] != 0:
                q = r[1] // piv[1]
                r[0] -= q * piv[0]
                r[1] -= q * piv[1]
    nz = [r for r in rows if r[1] != 0]
    if len(nz) != 1:
        raise ValueError("rank < 2")
    bx, c = nz[0]
    if c < 0:
        bx, c = -bx, -c
    a = 0
    for r in rows:
        if r[1] == 0:
            a = gcd(a, abs(r[0]))
    if a == 0:
        raise ValueError("rank < 2")
    return a, bx % a, c


def lat(vecs):
    """Canonical form (d, a, b, c) of the Z-lattice spanned by rational vectors; None for the zero lattice."""
    vecs = [(Fr(x), Fr(y)) for (x, y) in vecs if not (x == 0 and y == 0)]
    if not vecs:
        return None
    d = 1
    for x, y in vecs:
        d = lcm(d, x.denominator)
        d = lcm(d, y.denominator)
    iv = [(int(x * d), int(y * d)) for (x, y) in vecs]
    a, b, c = hnf(iv)
    g = gcd(gcd(a, b), gcd(c, d))
    return (d // g, a // g, b // g, c // g)


def basis(L):
    d, a, b, c = L
    return [(Fr(a, d), Fr(0)), (Fr(b, d), Fr(c, d))]


def member(v, L):
    if L is None:
        return iszero(v)
    d, a, b, c = L
    x, y = v[0] * d, v[1] * d
    if x.denominator != 1 or y.denominator != 1:
        return False
    x, y = int(x), int(y)
    if y % c:
        return False
    k = y // c
    return (x - k * b) % a == 0


def lcontains(big, small):
    """small is inside big."""
    if small is None:
        return True
    if big is None:
        return False
    return all(member(v, big) for v in basis(small))


def lsum(*Ls):
    vs = []
    for L in Ls:
        if L is not None:
            vs += basis(L)
    return lat(vs)


def ideal(*gens):
    """The O_K-ideal generated by the given elements, as a Z-lattice (generators g and g w)."""
    vs = []
    for g in gens:
        vs += [g, emul(g, W)]
    return lat(vs)


def iprod(I, J):
    if I is None or J is None:
        return None
    return lat([emul(x, y) for x in basis(I) for y in basis(J)])


def iscale(alpha, I):
    if I is None or iszero(alpha):
        return None
    return lat([emul(alpha, v) for v in basis(I)])


def inorm(I):
    """Index-based norm: [O : I] for integral I, extended by N((1/d) L) = det(L) / d^2."""
    d, a, b, c = I
    return Fr(a * c, d * d)


def iconj(I):
    return lat([econj(v) for v in basis(I)])


def iinv(I):
    return iscale(el(Fr(1) / inorm(I)), iconj(I))


def is_ideal(L):
    return all(member(emul(v, W), L) for v in basis(L))


def tdual(L):
    """Dual lattice for the trace form: {y in K : Tr(x y) in Z for all x in L}."""
    # Tr((x + x' w)(y1 + y2 w)) = 2 x y1 - 10 x' y2. Rows of A are (2 x_i, -10 x'_i); dual basis = columns of A^-1.
    (x1, u1), (x2, u2) = basis(L)
    A = [[2 * x1, -10 * u1], [2 * x2, -10 * u2]]
    det = A[0][0] * A[1][1] - A[0][1] * A[1][0]
    inv = [[A[1][1] / det, -A[0][1] / det], [-A[1][0] / det, A[0][0] / det]]
    return lat([(inv[0][0], inv[1][0]), (inv[0][1], inv[1][1])])


def iinter(I, J):
    """Intersection of two full-rank lattices: the dual of the sum of the duals."""
    return tdual(lsum(tdual(I), tdual(J)))


def principal_generator(I):
    """An alpha with alpha O = I, or None. Test: alpha in I with N(alpha) = N(I) (see seams.md, K.2)."""
    d = I[0]
    n = inorm(I) * d * d  # norm of the integral ideal d I
    n = int(n)
    dI = iscale(el(d), I)
    for y in range(-isqrt(n // 5) - 1, isqrt(n // 5) + 2):
        r = n - 5 * y * y
        if r < 0:
            continue
        x = isqrt(r)
        if x * x != r:
            continue
        for xx in {x, -x}:
            v = el(xx, y)
            if member(v, dI):
                return (Fr(xx, d), Fr(y, d))
    return None


O = ideal(ONE)
P = ideal(el(2), el(1, 1))
Q3a = ideal(el(3), el(1, 1))
Q3b = ideal(el(3), el(1, -1))
Q5 = ideal(W)
Q7a = ideal(el(7), el(3, 1))
Q7b = ideal(el(7), el(-3, 1))


def ideals_of_norm(n):
    """All integral O_K-ideals of index n, by enumerating Hermite normal forms (a, b, c), a c = n."""
    out = []
    for c in range(1, n + 1):
        if n % c:
            continue
        a = n // c
        for b in range(a):
            L = lat([(a, 0), (b, c)])
            if is_ideal(L) and L not in out and inorm(L) == n:
                out.append(L)
    return out


def rand_el(rng, num=6, den=3):
    return (Fr(rng.randint(-num, num), rng.randint(1, den)), Fr(rng.randint(-num, num), rng.randint(1, den)))


def rand_nonzero_el(rng, num=6, den=3):
    while True:
        a = rand_el(rng, num, den)
        if not iszero(a):
            return a


def rand_ideal(rng, zero_ok=False):
    if zero_ok and rng.random() < 0.15:
        return None
    gens = [rand_nonzero_el(rng, 5, 2) for _ in range(rng.randint(1, 2))]
    return ideal(*gens)


def rule_sum(I, J):
    return lsum(I, J)


def rule_mul(a, I, b, J):
    """Radius of the product ball: a J + b I + I J (seams.md, K.3)."""
    parts = []
    if J is not None and not iszero(a):
        parts.append(iscale(a, J))
    if I is not None and not iszero(b):
        parts.append(iscale(b, I))
    if I is not None and J is not None:
        parts.append(iprod(I, J))
    return lsum(*parts) if parts else None


def rule_mul_mutant(a, I, b, J):
    """Wrong rule without the term I J."""
    parts = []
    if J is not None and not iszero(a):
        parts.append(iscale(a, J))
    if I is not None and not iszero(b):
        parts.append(iscale(b, I))
    return lsum(*parts) if parts else None


def sample_ball(a, I, K=2):
    if I is None:
        return [a]
    e1, e2 = basis(I)
    return [eadd(a, eadd(emul(el(i), e1), emul(el(j), e2))) for i in range(-K, K + 1) for j in range(-K, K + 1)]


def check_ball_rule(a, I, b, J, rule, op, rhs_centre):
    """Containment of all sampled results in the predicted ball, and equality of the lattice spanned by the
    sampled differences with the predicted radius (tightness)."""
    c = rhs_centre
    R = rule
    diffs = [esub(op(x, y), c) for x in sample_ball(a, I) for y in sample_ball(b, J)]
    spanned = lat(diffs)
    contained = all(member(dv, R) for dv in diffs)
    return contained and spanned == R


def canon_ball(a, I):
    """Canonical form of a + I Ohat (seams.md, K.4): d least with d a in O and d I in O; L = d I in HNF; the centre
    d a reduced into the box 0 <= y < c, 0 <= x < a. Returns (d, x, y, A, B, C). I None: the point a."""
    if I is None:
        return ("point", a)
    d = 1
    for v in [a] + basis(I):
        d = lcm(d, v[0].denominator)
        d = lcm(d, v[1].denominator)
    L = iscale(el(d), I)
    assert L[0] == 1
    _, A, B, C = L
    x, y = int(a[0] * d), int(a[1] * d)
    k = y // C
    y -= k * C
    x -= k * B
    x %= A
    return (d, x, y, A, B, C)


def coset_set(a, I, m):
    """The ball a + I Ohat inside Ohat, as the set of its classes modulo m Ohat (requires m O inside I, a in O)."""
    out = set()
    for x in range(m):
        for y in range(m):
            if member(esub(el(x, y), a), I):
                out.add((x, y))
    return out


def phi(N):
    """|(O/N)^x| for an integral ideal N in canonical form (1, A, B, C), by enumeration of the HNF box."""
    _, A, B, C = N
    cnt = 0
    for y in range(C):
        for x in range(A):
            if lsum(ideal(el(x, y)), N) == O:
                cnt += 1
    return cnt


def part_K():
    print("--- K = Q(sqrt(-5)) ---")
    # K.1 the ideal P, its square, non-principality
    report("K1 P = (2, 1+w) in HNF", P == (1, 2, 1, 1), f"P = {P} (lattice Z(2,0) + Z(1,1)), N(P) = {inorm(P)}")
    report("K1 P^2 = (2)", iprod(P, P) == ideal(el(2)), f"P^2 = {iprod(P, P)}, (2) = {ideal(el(2))}")
    sols = [(x, y) for x in range(-2, 3) for y in range(-1, 2) if x * x + 5 * y * y == 2]
    report("K1 P not principal", principal_generator(P) is None and not sols,
           f"x^2 + 5 y^2 = 2 has {len(sols)} integer solutions")
    fac = {"(1+w) = P Q3a": ideal(el(1, 1)) == iprod(P, Q3a), "3 = Q3a Q3b": ideal(el(3)) == iprod(Q3a, Q3b),
           "Q3a != Q3b": Q3a != Q3b, "5 = Q5^2": ideal(el(5)) == iprod(Q5, Q5),
           "7 = Q7a Q7b": ideal(el(7)) == iprod(Q7a, Q7b),
           "Q3a, Q3b, Q7a, Q7b not principal": all(principal_generator(x) is None for x in (Q3a, Q3b, Q7a, Q7b)),
           "Q5 = (w) principal": principal_generator(Q5) is not None}
    report("K1 factorisations of 1+w, 3, 5, 7", all(fac.values()), f"{fac}")
    units = [(x, y) for x in range(-2, 3) for y in range(-1, 2) if x * x + 5 * y * y == 1]
    report("K1 units of O_K", sorted(units) == [(-1, 0), (1, 0)], f"x^2 + 5 y^2 = 1: {sorted(units)}")
    # K.2 index of a principal ideal equals the norm of its generator; norm multiplicative
    rng = random.Random(2)
    bad = 0
    for _ in range(300):
        al = rand_nonzero_el(rng)
        if inorm(iscale(al, O)) != enorm(al):
            bad += 1
    report("K2 N(alpha O) = N_{K/Q}(alpha)", bad == 0, f"300 random alpha, {bad} mismatches")
    bad = 0
    for _ in range(200):
        I, J = rand_ideal(rng), rand_ideal(rng)
        if inorm(iprod(I, J)) != inorm(I) * inorm(J):
            bad += 1
        if iprod(I, iinv(I)) != O:
            bad += 1
    report("K2 N(IJ) = N(I)N(J) and I * conj(I)/N(I) = O", bad == 0, f"200 random pairs, {bad} failures")
    # class group: every ideal of norm <= 60 is principal or in the class of P; both classes occur
    counts = {"principal": 0, "class of P": 0, "neither": 0}
    for n in range(1, 61):
        for I in ideals_of_norm(n):
            if principal_generator(I) is not None:
                counts["principal"] += 1
            elif principal_generator(iprod(I, P)) is not None:
                counts["class of P"] += 1
            else:
                counts["neither"] += 1
    report("K2 ideals of norm <= 60 lie in two classes", counts["neither"] == 0 and counts["class of P"] > 0,
           f"{counts}")
    # K.3 sum and product rules
    S = lsum(ideal(el(2)), ideal(el(1, 1)))
    report("K3 2 Ohat + (1+w) Ohat = P Ohat (a sum of principal radii is not principal)",
           S == P and principal_generator(S) is None, f"sum = {S}")
    Z6 = rule_mul(el(3), ideal(el(12)), el(5), ideal(el(18)))
    report("K3 Q example (3 mod 12)(5 mod 18) in K", Z6 == ideal(el(6)), f"radius {Z6} = 6 O_K")
    nsum = nmul = nmut = 0
    for trial in range(400):
        a, b = rand_el(rng), rand_el(rng)
        I, J = rand_ideal(rng, True), rand_ideal(rng, True)
        if trial < 5:
            a, b, I, J = el(0), el(0), P, P
            if trial > 0:
                a, b = rand_el(rng), rand_el(rng)
        if not check_ball_rule(a, I, b, J, rule_sum(I, J), eadd, eadd(a, b)):
            nsum += 1
        if not check_ball_rule(a, I, b, J, rule_mul(a, I, b, J), emul, emul(a, b)):
            nmul += 1
        if not check_ball_rule(a, I, b, J, rule_mul_mutant(a, I, b, J), emul, emul(a, b)):
            nmut += 1
    report("K3 sum rule (a+b) + (I+J): enclosure and tight", nsum == 0, f"400 random cases, {nsum} failures")
    report("K3 product rule ab + (aJ + bI + IJ): enclosure and tight", nmul == 0,
           f"400 random cases, {nmul} failures")
    report("K3 mutant (rule without IJ) is detected", nmut > 0, f"{nmut} of 400 cases fail")
    ok = check_ball_rule(el(0), P, el(0), P, iprod(P, P), emul, el(0)) and iprod(P, P) == ideal(el(2))
    ok2 = rule_mul(el(1), P, el(1), P) == P
    report("K3 (0 + P)(0 + P) = 0 + 2 Ohat tightly; (1 + P)(1 + P) inside 1 + P", ok and ok2, "")
    # K.4 canonical form: invariant under changes of representation
    bad = 0
    for _ in range(300):
        a, I = rand_el(rng), rand_ideal(rng)
        c0 = canon_ball(a, I)
        e1, e2 = basis(I)
        a2 = eadd(a, eadd(emul(el(rng.randint(-9, 9)), e1), emul(el(rng.randint(-9, 9)), e2)))
        f = rand_nonzero_el(rng, 4, 1)
        I2 = lat([emul(f, v) for v in basis(I)] + [emul(emul(f, W), v) for v in basis(I)])
        I2 = iscale(einv(f), I2)  # the same ideal, rebuilt from other generators
        c1 = canon_ball(a2, I2)
        if c0 != c1:
            bad += 1
        d, x, y, A, B, C = c0
        if gcd(gcd(gcd(x, y), gcd(A, B)), gcd(C, d)) != 1:
            bad += 1
    report("K4 canonical form independent of representation; gcd(x, y, A, B, C, d) = 1", bad == 0,
           f"300 random balls, {bad} failures")
    # K.5 predicates against enumeration modulo m O
    agree = total = 0
    ntrue = [0, 0, 0]
    for _ in range(250):
        I = rand_integral_ideal(rng)
        J = rand_integral_ideal(rng)
        m = lcm(I[1], J[1])
        if m > 24:
            continue
        a = el(rng.randint(0, m - 1), rng.randint(0, m - 1))
        b = el(rng.randint(0, m - 1), rng.randint(0, m - 1))
        if rng.random() < 0.3:
            b = eadd(a, basis(I)[rng.randint(0, 1)])
        SA, SB = coset_set(a, I, m), coset_set(b, J, m)
        eq_rule = (I == J) and member(esub(a, b), I)
        ov_rule = member(esub(a, b), lsum(I, J))
        ct_rule = lcontains(J, I) and member(esub(a, b), J)
        total += 1
        ntrue[0] += SA == SB
        ntrue[1] += bool(SA & SB)
        ntrue[2] += SA <= SB
        if eq_rule == (SA == SB) and ov_rule == bool(SA & SB) and ct_rule == (SA <= SB):
            agree += 1
    report("K5 equal_set, overlaps, contains with ideals vs enumeration", agree == total and min(ntrue) > 0,
           f"{agree} of {total} pairs agree; true outcomes (equal, overlap, contained) = {ntrue}")
    # K.6 unit cosets: |(O/N)^x| and the canonical-form rule
    three = ideal(el(3))
    r = {"phi(P)": phi(P), "phi(P^2)": phi(iprod(P, P)), "phi(3)": phi(three), "phi(3P)": phi(iprod(three, P)),
         "phi(6)": phi(ideal(el(6))), "phi(Q7a)": phi(Q7a), "phi(Q7a P)": phi(iprod(Q7a, P)),
         "phi(Q5)": phi(Q5), "phi(Q5 P)": phi(iprod(Q5, P))}
    ok = (r["phi(P)"] == 1 and r["phi(P^2)"] == 2 and r["phi(3P)"] == r["phi(3)"] and r["phi(6)"] == 2 * r["phi(3)"]
          and r["phi(Q7a P)"] == r["phi(Q7a)"] and r["phi(Q5 P)"] == r["phi(Q5)"])
    report("K6 U(P n) = U(n) for n prime to P; U(2n) != U(n) (the Q rule 'halve 2 x odd' is wrong in K)", ok,
           f"{r}")
    # K.7 different and character
    Dinv = tdual(O)
    Diff = iinv(Dinv)
    report("K7 different: dual of O under the trace is (2w)^-1 O; N(D) = 20 = |disc|",
           Dinv == iscale(einv(emul(el(2), W)), O) and inorm(Diff) == 20, f"dual(O) = {Dinv}, D = {Diff}")
    bad = 0
    for I in [P, Q3a, Q7b, iprod(P, Q5), ideal(el(Fr(1, 2)))] + [rand_ideal(rng) for _ in range(40)]:
        if tdual(I) != iprod(iinv(I), Dinv):
            bad += 1
    report("K7 trace dual of I equals I^-1 D^-1", bad == 0, f"45 ideals, {bad} failures")
    half = ideal(el(Fr(1, 2)))
    report("K7 psi_K is trivial on (1/2) Ohat although 1/2 is not integral", lcontains(Dinv, half),
           "Tr((1/2) O) = Z")
    # K.8 splitting a fractional radius: [I : I cap O] = [I + O : O]
    I = iscale(el(Fr(1, 2)), P)
    Ic = iinter(I, O)
    idx1 = inorm(Ic) / inorm(I)
    idx2 = inorm(O) / inorm(lsum(I, O))
    report("K8 pieces of a + (P/2) Ohat: [I : I cap O] = [I + O : O]", idx1 == idx2,
           f"{idx1} pieces, I cap O = {Ic}")
    # K.9 reconstruction: shortest vector of sigma(P)
    best = min(enorm(eadd(emul(el(i), basis(P)[0]), emul(el(j), basis(P)[1])))
               for i in range(-6, 7) for j in range(-6, 7) if (i, j) != (0, 0))
    report("K9 lambda_1(sigma(P))^2 = min N(x), x in P nonzero", best == 4, f"min norm {best}, lambda_1 = 2")
    # K.10 scaled policy: no principal ideal equals 3P; minimal principal enclosures 3 P Q^-1 are incomparable
    threeP = iprod(three, P)
    cands = {}
    for name, Qi in [("P", P), ("Q3a", Q3a), ("Q3b", Q3b), ("Q7a", Q7a), ("Q7b", Q7b)]:
        G = iprod(threeP, iinv(Qi))
        cands[name] = (G, principal_generator(G))
    ok = principal_generator(threeP) is None and all(g is not None for (_, g) in cands.values())
    ok = ok and all(lcontains(G, threeP) for (G, _) in cands.values())
    incomparable = all(not lcontains(cands[x][0], cands[y][0]) for x in cands for y in cands if x != y)
    gens = {k: (str(v[1][0]) + " + " + str(v[1][1]) + " w") for k, v in cands.items()}
    report("K10 scaled sum 2(u+3O) + (1+w)(v+3O): tight radius 3P not principal; enclosures 3PQ^-1 incomparable",
           ok and incomparable, f"generators {gens}")


def rand_integral_ideal(rng):
    gens = [el(rng.randint(-6, 6), rng.randint(-3, 3)) for _ in range(rng.randint(1, 2))]
    gens = [g for g in gens if not iszero(g)] or [el(1, 1)]
    return ideal(*gens)


# ==================================================================================================================
# Part F: F = F_3(T)
# ==================================================================================================================

try:
    from flint import nmod_poly
except ImportError:  # pragma: no cover
    nmod_poly = None

q = 3


def poly(cs):
    return nmod_poly([c % q for c in cs], q)


Tpol = None
ZERO = None
ONEp = None


def monic(p):
    lc = int(p.leading_coefficient())
    return p * pow(lc, -1, q), lc


class RF:
    """Rational function num/den over F_3, den monic, gcd 1."""

    def __init__(self, num, den=None):
        if den is None:
            den = ONEp
        if den.is_zero():
            raise ZeroDivisionError
        g = num.gcd(den) if not num.is_zero() else den
        num = num // g
        den = den // g
        den, lc = monic(den)
        num = num * pow(lc, -1, q)
        self.num, self.den = num, den

    def __add__(s, o):
        return RF(s.num * o.den + o.num * s.den, s.den * o.den)

    def __sub__(s, o):
        return RF(s.num * o.den - o.num * s.den, s.den * o.den)

    def __mul__(s, o):
        return RF(s.num * o.num, s.den * o.den)

    def __truediv__(s, o):
        return RF(s.num * o.den, s.den * o.num)

    def __eq__(s, o):
        return s.num == o.num and s.den == o.den

    def iszero(s):
        return s.num.is_zero()

    def is_poly(s):
        return s.den.is_one()

    def lc(s):
        """Leading coefficient at infinity (the 'sign': the unit part of the expansion in s)."""
        return int(s.num.leading_coefficient()) * pow(int(s.den.leading_coefficient()), -1, q) % q

    def v_inf(s):
        return s.den.degree() - s.num.degree()


def rfgcd(xs):
    """Monic generator of the F_3[T]-module generated by rational functions (0 if all are 0)."""
    xs = [x for x in xs if not x.iszero()]
    if not xs:
        return RF(ZERO)
    D = ONEp
    for x in xs:
        D = D * x.den // D.gcd(x.den)
    g = ZERO
    for x in xs:
        g = g.gcd(x.num * (D // x.den)) if not g.is_zero() else monic(x.num * (D // x.den))[0]
    return RF(g, D)


def divides(G, x):
    """x lies in G F_3[T] (G a rational function, not 0)."""
    return (x / G).is_poly()


def laurent_inf(f, n):
    """Coefficients {k: c_k} of f = sum c_k s^k, s = 1/T, for v_inf(f) <= k < n."""
    if f.iszero():
        return {}
    v = f.v_inf()
    if n <= v:
        return {}
    nr = f.num.reverse()  # num(T) = T^deg num * nr(s)
    dr = f.den.reverse()
    L = n - v
    ser = (nr * dr.inverse_series_trunc(L)).truncate(L)
    cs = ser.coeffs()
    return {v + i: int(cs[i]) for i in range(len(cs)) if int(cs[i]) != 0}


def res_inf(f):
    """Res_inf(f dT) = - c_1, since dT = - s^-2 ds (seams.md, F.6)."""
    return (-laurent_inf(f, 2).get(1, 0)) % q


def res_linear(f, c):
    """Res at T = c of f dT: coefficient of u^-1 in the expansion in u = T - c."""
    sh = poly([c, 1])
    num = f.num.compose(sh)
    den = f.den.compose(sh)
    m = 0
    cs = den.coeffs()
    while int(cs[m]) == 0:
        m += 1
    if m == 0:
        return 0
    h1 = den.right_shift(m) if hasattr(den, "right_shift") else den // poly([0] * m + [1])
    ser = (num * h1.inverse_series_trunc(m)).truncate(m)
    cs = ser.coeffs()
    return int(cs[m - 1]) % q if len(cs) >= m else 0


def trace_mod(e, Pp):
    """Trace from F_3[T]/(P) to F_3 of the class of e."""
    d = Pp.degree()
    t = 0
    for i in range(d):
        prod = (e * poly([0] * i + [1])) % Pp
        cs = prod.coeffs()
        t += int(cs[i]) if len(cs) > i else 0
    return t % q


def res_simple(f, Pp):
    """Res at an irreducible P of f dT when f has at most a simple pole at P: Tr((num / (h P'))(theta))."""
    den = f.den
    if not (den % Pp).is_zero():
        return 0
    h = den // Pp
    assert not (h % Pp).is_zero(), "res_simple needs a simple pole"
    e =(h * Pp.derivative()) % Pp
    g, sI, _ = e.xgcd(Pp)
    inv = sI * pow(int(g.leading_coefficient()), -1, q)
    return trace_mod((f.num * inv) % Pp, Pp)


def part_F():
    print("--- F = F_3(T) ---")
    T = RF(Tpol)
    rng = random.Random(3)
    # F.1 multiplication by T moves precision between the affine places and infinity
    vT = 0
    num = T.num
    while (num % Tpol).is_zero():
        num = num // Tpol
        vT += 1
    report("F1 v_T(T) = 1 and v_inf(T) = -1", vT == 1 and T.v_inf() == -1,
           f"v_T = {vT}, v_inf = {T.v_inf()}: a polynomial radius cannot record the loss at infinity")
    # F.2 affine product rule with monic gcd
    def rpoly(dmax):
        return poly([rng.randint(0, 2) for _ in range(rng.randint(0, dmax + 1))])

    def rrf(dn=3, dd=2, zero_ok=True):
        n = rpoly(dn)
        if not zero_ok and n.is_zero():
            n = ONEp
        dden = rpoly(dd)
        if dden.is_zero():
            dden = ONEp
        return RF(n, dden)

    def rmonic(dmax):
        """A random monic polynomial of degree 0..dmax."""
        return monic(poly([rng.randint(0, 2) for _ in range(rng.randint(0, dmax))] + [rng.randint(1, 2)]))[0]

    samples = [poly(c) for c in ([], [1], [2], [0, 1], [1, 1], [0, 2, 1], [1, 0, 0, 1])]
    bad = mut = 0
    for _ in range(300):
        a, b = rrf(), rrf()
        N = RF(ZERO) if rng.random() < 0.15 else RF(rmonic(3), rmonic(2))
        M = RF(rmonic(3), rmonic(2))
        G = rfgcd([a * M, b * N, N * M])
        Gm = rfgcd([a * M, b * N])
        diffs = [(a + N * RF(k)) * (b + M * RF(l)) - a * b for k in samples for l in samples]
        Gs = rfgcd(diffs)
        if G.iszero():
            ok = all(d.iszero() for d in diffs)
        else:
            ok = all(divides(G, d) for d in diffs) and Gs == G
        bad += not ok
        if Gm.iszero():
            mut += not all(d.iszero() for d in diffs)
        else:
            mut += not (all(divides(Gm, d) for d in diffs) and Gs == Gm)
    report("F2 affine product rule ab + gcd(aM, bN, NM) (monic gcd): enclosure and tight", bad == 0,
           f"300 random cases, {bad} failures")
    report("F2 mutant (without NM) is detected", mut > 0, f"{mut} of 300 cases fail")
    # F.3 product rule at infinity: radius exponent min(v(a)+m, v(b)+n, n+m)
    S = 12  # common shift: an element is p(s) / s^S with p a polynomial in s

    def ser(v, cs):
        return poly([0] * (v + S) + cs)

    def val(p, shift):
        if p.is_zero():
            return None
        cs = p.coeffs()
        k = 0
        while int(cs[k]) == 0:
            k += 1
        return k - shift

    bad = 0
    for _ in range(300):
        va, vb = rng.randint(-3, 3), rng.randint(-3, 3)
        n, m = rng.randint(-3, 4), rng.randint(-3, 4)
        A = ser(va, [rng.randint(1, 2)] + [rng.randint(0, 2) for _ in range(3)])
        B = ser(vb, [rng.randint(1, 2)] + [rng.randint(0, 2) for _ in range(3)])
        if rng.random() < 0.1:
            A = poly([])
            va = None
        pred = min(x for x in [(va + m) if va is not None else None, vb + n, n + m] if x is not None)
        vals = []
        for k in ([], [1], [2], [0, 1], [1, 1, 2]):
            for l in ([], [1], [2], [0, 1], [2, 0, 1]):
                X = A + ser(n, k) if k else A
                Y = B + ser(m, l) if l else B
                D = X * Y - A * B
                vv = val(D, 2 * S)
                if vv is not None:
                    vals.append(vv)
        bad += not (vals and min(vals) == pred)
    report("F3 product at infinity: radius s^min(v(a)+m, v(b)+n, n+m), enclosure and tight", bad == 0,
           f"300 random cases, {bad} failures")
    # F.4 A_F = F (+) (Ohat_aff x s F_3[[s]]): F cap the domain is 0
    cnt = 0
    for deg in range(0, 5):
        for _ in range(50):
            p = poly([rng.randint(0, 2) for _ in range(deg)] + [rng.randint(1, 2)])
            if RF(p).v_inf() >= 1:
                cnt += 1
    report("F4 no non-zero polynomial has v_inf >= 1 (uniqueness of the fundamental domain)", cnt == 0,
           f"250 polynomials, {cnt} counterexamples")
    # pieces: a ball c + s^n O_inf with n <= 0 meets q^(1-n) polynomial parts
    ok = True
    for n in range(-2, 2):
        parts = set()
        for coeffs in range(q ** 4):
            ks = [(coeffs // q ** i) % q for i in range(4)]  # coefficients of s^n, ..., s^(n+3)
            poly_part = tuple(ks[i] for i in range(4) if n + i <= 0)
            parts.add(poly_part)
        ok &= len(parts) == (q ** (1 - n) if n <= 0 else 1)
    report("F4 a ball at infinity with radius s^n, n <= 0, splits into q^(1-n) pieces", ok, "n = -2..1")
    # F.5 residue theorem for f dT
    lin = [0, 1, 2]
    quads = [poly([1, 0, 1]), poly([2, 1, 1])]
    assert all(len(qd.factor()[1]) == 1 and qd.factor()[1][0][1] == 1 for qd in quads)
    bad = mut = quad_nonzero = 0
    for _ in range(300):
        den = ONEp
        for c in lin:
            den = den * poly([-c, 1]) ** rng.randint(0, 3)
        for qd in quads:
            if rng.random() < 0.5:
                den = den * qd
        f = RF(rpoly(8), den)
        if f.iszero():
            continue
        rq = [res_simple(f, qd) for qd in quads]
        quad_nonzero += any(rq)
        tot = sum(res_linear(f, c) for c in lin) + sum(rq)
        bad += (tot + res_inf(f)) % q != 0
        mut += (tot - res_inf(f)) % q != 0
    report("F5 residue theorem: sum over all places of Res(f dT) = 0", bad == 0 and quad_nonzero > 0,
           f"300 random f ({quad_nonzero} with a non-zero residue at a place of degree 2), {bad} failures")
    report("F5 mutant (wrong sign of Res_inf) is detected", mut > 0, f"{mut} of 300 fail")
    # F.6 character values and determination on balls at infinity: psi_inf(x) = psi_0(-x_1)
    ok = True
    for n in range(-1, 4):
        vals = set()
        for coeffs in range(q ** 4):
            ks = [(coeffs // q ** i) % q for i in range(4)]  # coefficients of s^n..s^(n+3)
            x1 = ks[1 - n] if 0 <= 1 - n < 4 else 0
            vals.add((-x1) % q)
        ok &= (len(vals) == 1) == (n >= 2) and len(vals) in (1, q)
    report("F6 psi_inf is constant on c + s^n O_inf exactly when n >= 2 = -v_inf(dT); else all 3 values", ok,
           "n = -1..3")
    # F.7 reconstruction: |F cap (a + N Ohat_aff) cap (c + s^n O_inf)| is 0, 1 or q^(1 - n - deg N)
    # Every solution a + N gg has deg(N gg) <= max(-v_inf(a - g), -n) (otherwise v_inf = -deg(N gg) < n), so the
    # enumeration of gg up to degree B is complete when that bound minus deg N is at most B; other cases are
    # skipped.
    bad = tried = nonempty = several = 0
    B = 6
    polys = [poly([(idx // q ** i) % q for i in range(B + 1)]) for idx in range(q ** (B + 1))]
    for _ in range(60):
        a = rrf(2, 2)
        N = rmonic(2)
        n = rng.randint(-3, 3)
        g = rrf(3, 2)
        h = a - g
        bound = max(-h.v_inf() if not h.iszero() else -n, -n) - N.degree()
        if bound > B:
            continue
        cnt = 0
        for gg in polys:
            x = h + RF(N * gg)
            if x.iszero() or x.v_inf() >= n:
                cnt += 1
        e = 1 - n - N.degree()
        tried += 1
        nonempty += cnt > 0
        several += cnt > 1
        okc = (cnt <= 1) if e <= 0 else cnt in (0, q ** e)
        bad += not okc
    report("F7 reconstruction count 0, 1 (n + deg N >= 1) or q^(1-n-deg N)", bad == 0 and several > 0,
           f"{tried} cases ({nonempty} non-empty, {several} with several solutions), {bad} failures")
    # F.8 Pic^0 trivial and the product formula
    bad = 0
    irr = [poly([0, 1]), poly([1, 1]), poly([2, 1]), poly([1, 0, 1]), poly([2, 1, 1]), poly([2, 2, 1])]
    for _ in range(200):
        ns = [rng.randint(-3, 3) for _ in irr]
        f = RF(ONEp)
        for Pp, k in zip(irr, ns):
            f = f * (RF(Pp ** k) if k >= 0 else RF(ONEp, Pp ** (-k)))
        n_inf = -sum(k * Pp.degree() for Pp, k in zip(irr, ns))
        bad += f.v_inf() != n_inf
    report("F8 every divisor of degree 0 is div(prod P^n_P): Pic^0(P^1) = 0", bad == 0,
           f"200 divisors, {bad} failures")
    # F.9 idele class coordinates (t, u') are invariant under multiplication by F^x
    bad = 0
    for _ in range(200):
        g = rrf(3, 3, zero_ok=False)       # x_inf (an element of F_3((1/T)), here a rational function)
        r = RF(rmonic(2), rmonic(2))       # the monic scale of the affine part
        Nmod = poly([1, 1, 0, 1])          # modulus of the unit coset (T^3 + T + 1)
        c = poly([1, 2])
        while not c.gcd(Nmod).is_one():
            c = c + ONEp
        f = rrf(3, 3, zero_ok=False)

        def cls(g, r, c):
            sg = (g / r).lc()
            t = g / (r * RF(poly([sg])))
            u = (c * pow(sg, -1, q)) % Nmod
            return t, u

        t1, u1 = cls(g, r, c)
        fm, flc = monic(f.num)
        fm2, flc2 = monic(f.den)
        lcf = flc * pow(flc2, -1, q) % q
        r2 = r * RF(fm, fm2)
        c2 = (c * lcf) % Nmod
        t2, u2 = cls(g * f, r2, c2)
        bad += not (t1 == t2 and u1 == u2 and t1.lc() == 1)
    report("F9 idele class (t monic at infinity, u' = u / sgn) invariant under F^x", bad == 0,
           f"200 random ideles and multipliers, {bad} failures")
    # F.10 unit groups of F_3[T]/N never collapse (no residue field F_2)
    def phiF(N):
        d = N.degree()
        cnt = 0
        for idx in range(q ** d):
            c = poly([(idx // q ** i) % q for i in range(d)])
            if not c.is_zero() and c.gcd(N).is_one():
                cnt += 1
        return cnt
    vals = {"T": phiF(poly([0, 1])), "T^2": phiF(poly([0, 0, 1])), "T(T+1)": phiF(poly([0, 1, 1]))}
    report("F10 |(F_3[T]/N)^x|: U(P N) != U(N) always for q = 3", vals == {"T": 2, "T^2": 6, "T(T+1)": 4},
           f"{vals}")


if __name__ == "__main__":
    part_K()
    if nmod_poly is None:
        report("F part", False, "python-flint not importable")
    else:
        Tpol = nmod_poly([0, 1], q)
        ZERO = nmod_poly([], q)
        ONEp = nmod_poly([1], q)
        part_F()
    print(f"{len(FAILURES)} failures")
    sys.exit(1 if FAILURES else 0)
