#!/usr/bin/env python3
"""Writes tests/golden/gauss.tsv: the Gauss sum tau(chi) and the root number W_chi of the primitive character
of an adf_char, with the normalisation of docs/proofs/analysis.md Lemma 8 and Proposition 13:

    tau(chi) = sum_(a mod C) chi(a) E(a/C),    W_chi = tau(chi) / (i^e sqrt(C)),    chi(-1) = (-1)^e.

Unlike write_golden.py this computes: character values from python-flint (exact angles chi_exponent(x) /
exponent of the group), the sums with mpmath at 60 digits. Each value is written as a ball of the value form
(docs/conventions.md 9.5, 20 digits) around a 45-digit rounding with radius 1e-40. proto/test_text_grammar.py
recomputes the sums at 90 digits and checks containment; the lane report records a check against FLINT's
acb_dirichlet_gauss_sum. Run from the repository root.
"""
import os
import sys
from fractions import Fraction
from math import gcd

import flint
import mpmath

sys.path.insert(0, "proto")
import text_grammar as tg  # noqa: E402

mpmath.mp.dps = 60

CHARS = [(1, 1), (3, 2), (4, 3), (5, 2), (5, 3), (5, 4), (7, 3), (7, 6), (8, 3), (8, 5), (8, 7), (12, 11),
         (13, 2), (15, 2), (16, 3), (9, 2)]
EXTRA = [(10, 3)]   # not primitive: lowered to (5, 3) by the parser, and the Gauss sum is that of (5, 3)


def tau_w(q, n):
    if q == 1:
        return mpmath.mpc(1), mpmath.mpc(1), 0
    c = flint.dirichlet_char(q, n)
    assert int(c.conductor()) == q
    ex = int(flint.dirichlet_group(q).exponent())
    e = int(c.parity())
    tau = mpmath.mpc(0)
    for a in range(1, q + 1):
        if gcd(a, q) != 1:
            continue
        ang = Fraction(int(c.chi_exponent(a)), ex) + Fraction(a, q)
        tau += mpmath.expjpi(2 * mpmath.mpf(ang.numerator) / ang.denominator)
    w = tau / (mpmath.mpc(0, 1) ** e * mpmath.sqrt(q))
    return tau, w, e


def ball(x):
    mid = Fraction(mpmath.nstr(x, 45))
    return tg.print_real(mid, Fraction(1, 10 ** 40), 20)


def cball(z):
    return "(%s) + (%s)*i" % (ball(z.real), ball(z.imag))


def main():
    lines = ["# Gauss sum and root number of the primitive character of an adf_char (conventions 6.4);",
             "# generated by lanes/m0-conventions/gen_gauss.py (mpmath, 60 digits); balls enclose the exact values",
             "# expected: e=<parity> tau=<complex ball> W=<complex ball>"]
    for q, n in CHARS + EXTRA:
        f, m = tg._primitive_char(q, n)
        tau, w, e = tau_w(f, m)
        inp = "char(q=%d, n=%d, s=(0) + (0)*i)" % (q, n)
        lines.append("%s\te=%d tau=%s W=%s" % (inp, e, cball(tau), cball(w)))
    with open(os.path.join("tests", "golden", "gauss.tsv"), "w", encoding="ascii", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", len(CHARS) + len(EXTRA), "vectors")


if __name__ == "__main__":
    main()
