"""Exact rational helpers for the reference.

Only `fractions.Fraction` and Python integers are used. `qgcd` is the non-negative generator of
the subgroup of Q generated by its arguments; it is 0 exactly when all arguments are 0
(docs/proofs/precision.md, Lemma 2, and its use in Proposition 2).
"""
from fractions import Fraction
from functools import reduce
from math import gcd


def is_integer(x):
    """True when the rational x has no prime in its denominator."""
    return Fraction(x).denominator == 1


def qlcm(*xs):
    """Least common multiple of rationals in the divisibility order (0 if all are 0)."""
    vals = [Fraction(x) for x in xs]
    vals = [x for x in vals if x != 0]
    if not vals:
        return Fraction(0)
    num = 1
    for x in vals:
        num = num * x.numerator // gcd(num, x.numerator)
    den = 0
    for x in vals:
        den = gcd(den, x.denominator)
    return Fraction(num, den if den else 1)


def qgcd(*xs):
    """Non-negative generator of the subgroup of Q generated by xs (0 if all are 0)."""
    vals = [Fraction(x) for x in xs]
    vals = [x for x in vals if x != 0]
    if not vals:
        return Fraction(0)
    den = reduce(lambda a, b: a * b // gcd(a, b), [x.denominator for x in vals])
    num = reduce(gcd, [abs(int(x * den)) for x in vals])
    return Fraction(num, den)


def v_p(x, p):
    """Valuation of a non-zero rational at the prime p (p an integer > 1)."""
    x = Fraction(x)
    if x == 0:
        raise ValueError("v_p(0) is not defined")
    if p < 2:
        raise ValueError("p must be at least 2")
    e = 0
    while x.numerator % p == 0:
        x /= p
        e += 1
    while x.denominator % p == 0:
        x *= p
        e -= 1
    return e
