#!/usr/bin/env python3
"""scaled_oracle.py: checks the output of scaled_ops.c with exact arithmetic (fractions).

Sets: a ball c + R Zhat (R > 0) or a point c (R = 0), c, R rational. Containment and equality
are decided exactly: c + R Zhat contains c' + R' Zhat iff R'/R and (c' - c)/R are integers
(Zhat meets Q in Z); a ball contains a point c' iff (c' - c)/R is an integer.
Tight results are computed here from the input sets, not by the library:
  sum      (c1 + c2, gcd(R1, R2))
  product  (c1 c2, gcd(c1 R2, c2 R1, R1 R2))     (smallest ball containing all products)
  q x      (q c, |q| R);  x + q  (c + q, R);  -x  (-c, R)
The best scaled enclosure in modulus K of a ball (c, R), R > 0, is s (u + K Zhat) with
s = gcd(c, R/K) (the largest s with s | c and s K | R), u = c/s mod K.
Usage: python3 scaled_oracle.py out.txt
"""
import sys
from fractions import Fraction as F
from math import gcd


def qgcd(*xs):
    """non-negative generator of the subgroup of Q generated by xs"""
    g = F(0)
    for x in xs:
        x = abs(F(x))
        if g == 0:
            g = x
        elif x != 0:
            g = F(gcd(g.numerator * x.denominator, x.numerator * g.denominator),
                  g.denominator * x.denominator)
    return g


def isint(x):
    return F(x).denominator == 1


def contains(A, B):
    (ca, ra), (cb, rb) = A, B
    if ra == 0:
        return rb == 0 and ca == cb
    if rb == 0:
        return isint((cb - ca) / ra)
    return isint(rb / ra) and isint((cb - ca) / ra)


def equal(A, B):
    return contains(A, B) and contains(B, A)


def parse_sc(t, K):
    e, s, u = t.split(",")
    return int(e), F(s), int(u)


def ball_of(sc, K):
    e, s, u = sc
    return (s, F(0)) if e == 1 else (s * u, s * K)


def canonical(sc, K):
    e, s, u = sc
    if e == 1:
        return u == 0
    return s > 0 and 0 <= u < K


def t_add(A, B):
    return (A[0] + B[0], qgcd(A[1], B[1]))


def t_mul(A, B):
    return (A[0] * B[0], qgcd(A[0] * B[1], B[0] * A[1], A[1] * B[1]))


def best(Bl, K):
    c, R = Bl
    s = qgcd(c, R / K)
    return (0, s, int((c / s) % K))


fails = {}
counts = {}


def fail(op, line, why):
    fails.setdefault(op, []).append((why, line.strip()[:300]))


for line in open(sys.argv[1]):
    if not line or line.startswith("SUMMARY"):
        if line.startswith("SUMMARY"):
            print(line.strip())
        continue
    parts = line.split()
    op = parts[0]
    if op.endswith("BAD") or op in ("ALIASBAD", "DOMAINBAD", "LOCALBAD"):
        fail(op, line, "C-side check failed")
        continue
    kv = dict(p.split("=", 1) for p in parts[1:])
    counts[op] = counts.get(op, 0) + 1
    K = int(kv["K"])
    if op in ("add", "sub", "mul", "mul_tight"):
        X, Y, Z = (parse_sc(kv[k], K) for k in "XYZ")
        if int(kv["ST"]) != 0:
            fail(op, line, "status")
            continue
        if not canonical(Z, K):
            fail(op, line, "not canonical")
        bx, by, bz = ball_of(X, K), ball_of(Y, K), ball_of(Z, K)
        if op == "sub":
            by = (-by[0], by[1])
        tight = t_add(bx, by) if op in ("add", "sub") else t_mul(bx, by)
        if not contains(bz, tight):
            fail(op, line, "ENCLOSURE: result does not contain the tight result")
        if X[0] == 1 and Y[0] == 1:
            if Z[0] != 1 or Z[1] != tight[0]:
                fail(op, line, "exact inputs: exact tag or value lost")
        elif op in ("add", "sub"):
            if X[0] == 0 and Y[0] == 0:
                if not equal(bz, tight):
                    fail(op, line, "sum not tight")
            else:
                if Z != best(tight, K):
                    fail(op, line, "one exact operand: not the best scaled enclosure")
        elif op == "mul_tight":
            if not equal(bz, tight) and not (tight[1] == 0 and Z[0] == 1 and Z[1] == tight[0]):
                fail(op, line, "mul_tight not the tight product")
        elif op == "mul":
            if X[0] == 0 and Y[0] == 0:
                h = gcd(X[2], Y[2], K)
                if not equal(bz, (X[1] * Y[1] * X[2] * Y[2], X[1] * Y[1] * K)):
                    fail(op, line, "default product not s t (u v + K Zhat)")
                if tight[1] / bz[1] != h:
                    fail(op, line, "loss factor is not gcd(u, v, K)")
            else:
                if not equal(bz, tight) and not (tight[1] == 0 and Z[0] == 1 and Z[1] == tight[0]):
                    fail(op, line, "exact factor: not exact as a set")
    elif op in ("neg", "mul_rat", "add_rat"):
        X, Z = parse_sc(kv["X"], K), parse_sc(kv["Z"], K)
        bx, bz = ball_of(X, K), ball_of(Z, K)
        if not canonical(Z, K):
            fail(op, line, "not canonical")
        if op == "neg":
            tight = (-bx[0], bx[1])
        elif op == "mul_rat":
            q = F(kv["Q"])
            tight = (q * bx[0], abs(q) * bx[1])
        else:
            q = F(kv["Q"])
            tight = (bx[0] + q, bx[1])
        if not contains(bz, tight):
            fail(op, line, "ENCLOSURE")
        if tight[1] == 0:
            if Z[0] != 1 or Z[1] != tight[0]:
                fail(op, line, "exact result: tag or value")
        elif op in ("neg", "mul_rat"):
            if not equal(bz, tight):
                fail(op, line, "not exact as a set")
        else:
            if Z != best(tight, K):
                fail(op, line, "add_rat not the best enclosure")
            if int(kv["L"]) != (0 if equal(bz, tight) else 1):
                fail(op, line, "lost flag wrong")
        if op == "add_rat" and tight[1] == 0 and int(kv["L"]) != 0:
            fail(op, line, "lost flag wrong (exact)")
    elif op == "get_fball":
        X = parse_sc(kv["X"], K)
        A, H, d = (int(v) for v in kv["B"].split(","))
        if not equal((F(A, d), F(H, d)), ball_of(X, K)):
            fail(op, line, "get_fball changes the set")
    elif op in ("set_context", "set_context_alias"):
        K2 = int(kv["K2"])
        X, Z = parse_sc(kv["X"], K), parse_sc(kv["Z"], K2)
        bx, bz = ball_of(X, K), ball_of(Z, K2)
        if not canonical(Z, K2):
            fail(op, line, "not canonical")
        if not contains(bz, bx):
            fail(op, line, "ENCLOSURE")
        if X[0] == 1:
            if Z != X or int(kv["L"]) != 0:
                fail(op, line, "exact input: tag, value or lost")
        else:
            if Z != best(bx, K2):
                fail(op, line, "not the best enclosure")
            want = 0 if equal(bz, bx) else 1
            if int(kv["L"]) != want:
                fail(op, line, "lost = %s, but the set %s" % (kv["L"], "changed" if want else "did not change"))
    elif op == "set_fball":
        A, H, d = (int(v) for v in kv["B"].split(","))
        bx = (F(A, d), F(H, d))
        Z = parse_sc(kv["Z"], K)
        bz = ball_of(Z, K)
        if not canonical(Z, K):
            fail(op, line, "not canonical")
        if not contains(bz, bx):
            fail(op, line, "ENCLOSURE")
        if H == 0:
            if Z[0] != 1 or Z[1] != bx[0] or int(kv["L"]) != 0:
                fail(op, line, "exact input")
        else:
            if Z != best(bx, K):
                fail(op, line, "not the best enclosure")
            if int(kv["L"]) != (0 if equal(bz, bx) else 1):
                fail(op, line, "lost flag wrong")
    else:
        fail(op, line, "unknown record")

print("records checked:", sum(counts.values()), counts)
if not fails:
    print("no failure")
for op, lst in fails.items():
    print("FAIL %s: %d records" % (op, len(lst)))
    whys = {}
    for why, l in lst:
        whys.setdefault(why, []).append(l)
    for why, ls in whys.items():
        print("   %-60s %6d   e.g. %s" % (why, len(ls), ls[0][:200]))
sys.exit(1 if fails else 0)
